import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, ClipboardCheck, FileWarning, LoaderCircle, LogOut, Search, ShieldCheck, Upload, WalletCards } from 'lucide-react'
import { api, fileToBase64, openApiFile } from '../../services/api'

const statusLabel = { submitted: 'รอตรวจหนี้', debt_checked: 'รอตรวจห้อง', inspected: 'รออนุมัติ', approved: 'อนุมัติแล้ว', rejected: 'ตีกลับ' }
const fieldClass = 'h-10 w-full rounded-xl border border-[#d8e3e8] bg-white px-3 text-[11px] outline-none focus:border-[#0f766e] focus:ring-2 focus:ring-[#0f766e]/10'

function CheckoutDesk({ notify }) {
  const [requests, setRequests] = useState([])
  const [refunds, setRefunds] = useState([])
  const [selectedId, setSelectedId] = useState(null)
  const [query, setQuery] = useState('')
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const load = async () => {
    setLoading(true)
    try {
      const [requestRows, refundRows] = await Promise.all([api('/checkout-requests'), api('/checkouts')])
      setRequests(requestRows); setRefunds(refundRows); setSelectedId(current => current || requestRows[0]?.id || null)
    } catch (error) { notify(error.message) } finally { setLoading(false) }
  }
  useEffect(() => { load() }, [])
  const selected = requests.find(item => item.id === selectedId)
  const filtered = useMemo(() => requests.filter(item => `${item.request_no} ${item.tenant_code} ${item.first_name} ${item.last_name} ${item.room_no}`.toLowerCase().includes(query.toLowerCase())), [requests, query])
  const run = async (action, message) => { setSaving(true); try { await action(); notify(message); await load() } catch (error) { notify(error.message) } finally { setSaving(false) } }

  if (loading) return <div className="grid min-h-96 place-items-center"><LoaderCircle className="animate-spin text-[#0f766e]"/></div>
  return <div className="space-y-5">
    <header className="flex flex-col gap-3 rounded-3xl bg-[#16324f] p-6 text-white md:flex-row md:items-end md:justify-between"><div><p className="text-[9px] font-semibold uppercase tracking-[.18em] text-[#8fc2c7]">Checkout dossier · 4.5.7–4.5.8</p><h2 className="mt-2 text-2xl font-semibold">ย้ายออกและคืนเงินประกัน</h2><p className="mt-2 text-[11px] text-[#bed0dc]">ตรวจหนี้ ตรวจห้อง บันทึกมิเตอร์ อนุมัติ และแนบหลักฐานการคืนเงินในแฟ้มเดียว</p></div><div className="grid grid-cols-3 gap-2 text-center">{[['คำขอ',requests.length],['รอดำเนินการ',requests.filter(x=>!['approved','rejected'].includes(x.status)).length],['รอคืนเงิน',refunds.filter(x=>x.refund_transfer_status!=='transferred'&&Number(x.refund_amount)>0).length]].map(([label,value])=><div key={label} className="rounded-xl bg-white/8 px-4 py-3"><b className="block text-lg">{value}</b><small className="text-[8px] text-[#b9cbd6]">{label}</small></div>)}</div></header>
    <div className="grid gap-5 xl:grid-cols-[360px_minmax(0,1fr)]">
      <aside className="overflow-hidden rounded-2xl border border-[#dbe5e9] bg-white"><div className="border-b border-[#e6edef] p-4"><label className="flex items-center gap-2 rounded-xl bg-[#f2f6f7] px-3"><Search size={14} className="text-[#83949f]"/><input value={query} onChange={e=>setQuery(e.target.value)} className="h-10 w-full bg-transparent text-[11px] outline-none" placeholder="ค้นหาชื่อ ห้อง หรือเลขคำขอ"/></label></div><div className="max-h-[650px] divide-y divide-[#e9eef0] overflow-auto">{filtered.map(item=><button key={item.id} onClick={()=>setSelectedId(item.id)} className={`w-full p-4 text-left transition ${selectedId===item.id?'bg-[#edf7f4]':'hover:bg-[#f8fafb]'}`}><div className="flex items-start justify-between gap-3"><div><b className="font-['IBM_Plex_Sans'] text-[11px] text-[#28445a]">{item.request_no}</b><p className="mt-1 text-xs font-medium">{item.first_name} {item.last_name}</p><small className="mt-1 block text-[9px] text-[#83939e]">{item.building_name} · ห้อง {item.room_no} · ออก {date(item.requested_checkout_date)}</small></div><Badge status={item.status}/></div></button>)}{filtered.length===0&&<p className="p-8 text-center text-[10px] text-[#84949f]">ไม่พบคำขอย้ายออก</p>}</div></aside>
      <main>{selected ? <RequestDossier request={selected} refund={refunds.find(x=>x.id===selected.completed_checkout_id)} saving={saving} run={run}/> : <div className="grid min-h-96 place-items-center rounded-2xl border border-dashed border-[#cfdee5] bg-white text-center"><div><LogOut className="mx-auto text-[#9aabb5]"/><p className="mt-3 text-xs">เลือกคำขอเพื่อเริ่มตรวจสอบ</p></div></div>}</main>
    </div>
  </div>
}

function RequestDossier({ request, refund, saving, run }) {
  const inspect = event => { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget)); run(() => api(`/checkout-requests/${request.id}/inspection`, { method: 'POST', body: { inspectionNote: form.inspectionNote, waterReading: Number(form.waterReading), electricityReading: Number(form.electricityReading), damageDetail: form.damageDetail || null, damageAmount: Number(form.damageAmount || 0) } }), 'บันทึกผลตรวจห้องและออกใบแจ้งหนี้รอบสุดท้ายแล้ว') }
  const reject = event => { event.preventDefault(); const reason = new FormData(event.currentTarget).get('reason'); run(() => api(`/checkout-requests/${request.id}/reject`, { method: 'POST', body: { reason } }), 'ส่งคำขอกลับให้ผู้เช่าแล้ว') }
  const transfer = async event => { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget)); if (!form.file?.size) return; if (form.file.size > 3_000_000) throw new Error('ไฟล์ต้องไม่เกิน 3 MB'); const fileBase64 = await fileToBase64(form.file); return run(() => api(`/checkouts/${refund.id}/refund-transfer`, { method: 'POST', body: { referenceNo: form.referenceNo, transferredAt: new Date(form.transferredAt).toISOString(), filename: form.file.name, mimeType: form.file.type, fileBase64 } }), 'บันทึกผลโอนและแจ้งผู้เช่าแล้ว') }
  return <div className="overflow-hidden rounded-2xl border border-[#dbe5e9] bg-white"><div className="border-b border-[#e5ecef] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[9px] font-semibold uppercase tracking-[.15em] text-[#0f766e]">{request.request_no}</p><h3 className="mt-1 text-lg font-semibold">{request.first_name} {request.last_name}</h3><p className="mt-1 text-[10px] text-[#718493]">{request.tenant_code} · {request.building_name} ห้อง {request.room_no} เตียง {request.bed_no}</p></div><Badge status={request.status}/></div><div className="mt-5 grid grid-cols-4 gap-1"><Step active name="ยื่นคำขอ"/><Step active={request.status!=='submitted'} name="ตรวจหนี้"/><Step active={['inspected','approved'].includes(request.status)} name="ตรวจห้อง"/><Step active={request.status==='approved'} name="อนุมัติ"/></div></div>
    <div className="grid gap-5 p-5 lg:grid-cols-[1fr_330px]"><section className="space-y-4"><Info title="วันที่ขอย้ายออก" value={date(request.requested_checkout_date)}/><Info title="เหตุผล" value={request.reason}/>
      {request.status==='submitted'&&<Action icon={WalletCards} title="ขั้นที่ 1 · ตรวจสอบหนี้" detail="ระบบจะคำนวณยอดใบแจ้งหนี้คงเหลือของผู้เช่าอีกครั้ง"><button disabled={saving} onClick={()=>run(()=>api(`/checkout-requests/${request.id}/debt-review`,{method:'POST'}),'ตรวจสอบหนี้แล้ว')} className="primary">ตรวจหนี้จากระบบ</button></Action>}
      {request.status==='debt_checked'&&<form onSubmit={inspect} className="rounded-2xl border border-[#dce7ea] bg-[#f5f9fa] p-4"><h4 className="flex items-center gap-2 text-xs font-semibold"><ClipboardCheck size={15} className="text-[#0f766e]"/> ขั้นที่ 2 · ตรวจห้องและมิเตอร์วันย้ายออก</h4><p className="mt-2 text-[10px] text-[#728592]">ยอดค้างเมื่อตรวจครั้งล่าสุด <b className="text-[#b45309]">{money(request.outstanding_debt)} บาท</b></p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="เลขมิเตอร์น้ำ"><input required type="number" min="0" step="0.01" name="waterReading" className={fieldClass}/></Field><Field label="เลขมิเตอร์ไฟ"><input required type="number" min="0" step="0.01" name="electricityReading" className={fieldClass}/></Field><Field label="ความเสียหาย"><input name="damageDetail" className={fieldClass} placeholder="ไม่มี หรือระบุรายการ"/></Field><Field label="ยอดหักเงินประกัน"><input type="number" min="0" step="0.01" defaultValue="0" name="damageAmount" className={fieldClass}/></Field><div className="sm:col-span-2"><Field label="บันทึกผลตรวจ"><textarea required name="inspectionNote" rows="3" className={`${fieldClass} h-auto py-3`}/></Field></div></div><button disabled={saving} className="primary mt-4">บันทึกผลตรวจและคำนวณยอดสุดท้าย</button></form>}
      {request.status==='inspected'&&<Action icon={ShieldCheck} title="ขั้นที่ 3 · อนุมัติการย้ายออก" detail={`ค่าน้ำ–ไฟรอบสุดท้าย ${money(request.final_utility_amount)} บาท · ความเสียหาย ${money(request.damage_amount)} บาท${request.final_invoice_no?` · ใบแจ้งหนี้ ${request.final_invoice_no}`:''}`}><button disabled={saving} onClick={()=>run(()=>api(`/checkout-requests/${request.id}/approve`,{method:'POST'}),'อนุมัติย้ายออกและปล่อยเตียงแล้ว')} className="primary">ยืนยันว่าไม่มีหนี้และอนุมัติ</button></Action>}
      {request.status==='approved'&&<div className="rounded-2xl border border-[#bee1d7] bg-[#edf8f4] p-4"><h4 className="flex items-center gap-2 text-xs font-semibold text-[#176b58]"><CheckCircle2 size={16}/> อนุมัติการย้ายออกแล้ว</h4><p className="mt-2 text-[10px] text-[#557b70]">ห้องถูกตั้งเป็น “ไม่พร้อม” เพื่อรอตรวจความพร้อมก่อนเปิดจองครั้งถัดไป</p></div>}
    </section><aside className="space-y-4"><div className="rounded-2xl bg-[#16324f] p-5 text-white"><small className="text-[#a9bfcd]">เงินประกันตามสัญญา</small><b className="mt-1 block text-2xl">{money(request.deposit_amount)} บาท</b><div className="my-4 border-t border-white/10"/><p className="flex justify-between text-[10px]"><span>หักความเสียหาย</span><b className="text-[#f2c26d]">-{money(request.damage_amount)}</b></p><p className="mt-2 flex justify-between text-[10px]"><span>คงเหลือคืน</span><b>{money(refund?.refund_amount)} บาท</b></p></div>
      {refund&&Number(refund.refund_amount)>0&&(refund.refund_transfer_status==='transferred'?<div className="rounded-2xl border border-[#bee1d7] p-4"><b className="text-xs text-[#176b58]">โอนเงินประกันแล้ว</b><p className="mt-2 text-[10px] text-[#6c8177]">อ้างอิง {refund.refund_transfer_reference}<br/>{dateTime(refund.refund_transferred_at)}</p><button onClick={()=>openApiFile(`/checkouts/${refund.id}/refund-proof`)} className="secondary mt-3">ดูหลักฐานการโอน</button></div>:<form onSubmit={transfer} className="rounded-2xl border border-[#ead9ba] bg-[#fffaf0] p-4"><h4 className="text-xs font-semibold text-[#8a5a0a]">บันทึกการคืนเงินประกัน</h4><div className="mt-3 space-y-3"><Field label="เลขอ้างอิง"><input required name="referenceNo" className={fieldClass}/></Field><Field label="วันเวลาที่โอน"><input required type="datetime-local" name="transferredAt" className={fieldClass}/></Field><Field label="หลักฐาน"><input required type="file" name="file" accept="image/jpeg,image/png,application/pdf" className={`${fieldClass} h-auto py-2`}/></Field><button disabled={saving} className="primary w-full justify-center"><Upload size={13}/> บันทึกและแจ้งผู้เช่า</button></div></form>)}
      {['submitted','debt_checked'].includes(request.status)&&<form onSubmit={reject} className="rounded-2xl border border-[#efcfca] p-4"><Field label="เหตุผลที่ส่งกลับ"><textarea required minLength="5" name="reason" rows="3" className={`${fieldClass} h-auto py-2`}/></Field><button disabled={saving} className="secondary mt-3 border-[#e8bdb6] text-[#a84337]"><FileWarning size={13}/> ส่งกลับให้แก้ไข</button></form>}</aside></div>
  </div>
}

function Action({icon:Icon,title,detail,children}){return <div className="rounded-2xl border border-[#dce7ea] p-4"><div className="flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#e8f5f1] text-[#0f766e]"><Icon size={16}/></span><div><h4 className="text-xs font-semibold">{title}</h4><p className="mt-1 text-[10px] leading-5 text-[#718493]">{detail}</p><div className="mt-3">{children}</div></div></div></div>}
function Field({label,children}){return <label><span className="mb-1 block text-[9px] font-medium text-[#637989]">{label}</span>{children}</label>}
function Info({title,value}){return <div><small className="text-[9px] text-[#82919c]">{title}</small><p className="mt-1 text-[11px] leading-5 text-[#314d62]">{value||'-'}</p></div>}
function Step({active,name}){return <div className={`rounded-lg px-2 py-2 text-center text-[8px] font-medium ${active?'bg-[#dff3ec] text-[#176b58]':'bg-[#edf1f3] text-[#83919b]'}`}>{name}</div>}
function Badge({status}){return <span className={`shrink-0 rounded-full px-2 py-1 text-[8px] font-medium ${status==='approved'?'bg-[#ddf3eb] text-[#176b58]':status==='rejected'?'bg-[#fde8e5] text-[#a84337]':'bg-[#fff2d7] text-[#8a5a0a]'}`}>{statusLabel[status]||status}</span>}
function money(value){return Number(value||0).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2})}
function date(value){return value?new Date(value).toLocaleDateString('th-TH',{dateStyle:'medium'}):'-'}
function dateTime(value){return value?new Date(value).toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'}):'-'}

export default CheckoutDesk
