import { useState } from 'react'
import { Building2, Eye, EyeOff, KeyRound, LockKeyhole, ServerCog } from 'lucide-react'
import { login } from '../../services/api'

function Login({ onLogin }) {
  const [show,setShow]=useState(false); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
  const submit=async event=>{event.preventDefault();setLoading(true);setError('');const data=Object.fromEntries(new FormData(event.currentTarget));try{const user=await login(data.username,data.password);onLogin(user)}catch(err){setError(err.message)}finally{setLoading(false)}}
  return <div className="grid min-h-screen bg-[#eef3f6] lg:grid-cols-[1.05fr_.95fr]"><section className="relative hidden overflow-hidden bg-[#142a46] p-12 text-white lg:flex lg:flex-col"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-[#f5bf3c] text-[#142a46]"><Building2 size={23}/></div><div><p className="font-['IBM_Plex_Sans'] text-lg font-semibold">CAMPUS NEST</p><p className="text-[10px] text-[#aebccd]">Dormitory Management</p></div></div><div className="my-auto max-w-xl"><p className="text-[11px] font-medium tracking-[.14em] text-[#f5bf3c]">UNIVERSITY HOUSING OPERATIONS</p><h1 className="mt-4 text-4xl font-semibold leading-[1.25]">หนึ่งบัญชี<br/>ดูแลทุกชีวิตในหอพัก</h1><p className="mt-5 max-w-md text-sm leading-7 text-[#b8c8d5]">บริหารผู้พัก ห้อง การเงิน งานซ่อม และสต็อกด้วยข้อมูลที่ตรวจสอบย้อนหลังได้</p><div className="mt-10 grid grid-cols-3 gap-3">{[['90 วัน','History Log'],['LDAP','บัญชีกลาง'],['RBAC','สิทธิ์ตามหน้าที่']].map(x=><div key={x[0]} className="border-l border-white/20 pl-3"><p className="font-['IBM_Plex_Sans'] text-xl font-semibold text-[#f5bf3c]">{x[0]}</p><p className="mt-1 text-[10px] text-[#9fb1c1]">{x[1]}</p></div>)}</div></div><p className="text-[10px] text-[#738ba0]">ระบบบริหารจัดการหอพักมหาวิทยาลัย · Version 0.1.0</p></section>
  <main className="flex items-center justify-center p-6"><form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-[#dbe5ea] bg-white p-7 shadow-[0_16px_50px_rgba(22,45,68,.1)]"><div className="mb-7 lg:hidden"><div className="grid size-11 place-items-center rounded-xl bg-[#f5bf3c] text-[#142a46]"><Building2/></div></div><p className="text-[10px] font-medium text-[#41749e]">เข้าสู่ระบบเจ้าหน้าที่และผู้พัก</p><h2 className="mt-1 text-2xl font-semibold text-[#172f49]">ยืนยันตัวตนเพื่อดำเนินการต่อ</h2><p className="mt-2 text-xs text-[#7a8b99]">ใช้บัญชีมหาวิทยาลัย หรือบัญชี Local ที่ได้รับอนุญาต</p>
  <div className="mt-7 space-y-4"><label className="block"><span className="mb-1.5 block text-[10px] font-medium text-[#607586]">ชื่อผู้ใช้งาน</span><div className="flex h-11 items-center gap-2 rounded-xl border border-[#d6e1e7] px-3 focus-within:border-[#4c8fc8] focus-within:ring-2 focus-within:ring-[#4c8fc8]/15"><ServerCog size={16} className="text-[#718594]"/><input name="username" required autoComplete="username" className="w-full text-xs outline-none" placeholder="Username มหาวิทยาลัย"/></div></label><label className="block"><span className="mb-1.5 block text-[10px] font-medium text-[#607586]">รหัสผ่าน</span><div className="flex h-11 items-center gap-2 rounded-xl border border-[#d6e1e7] px-3 focus-within:border-[#4c8fc8] focus-within:ring-2 focus-within:ring-[#4c8fc8]/15"><LockKeyhole size={16} className="text-[#718594]"/><input name="password" required minLength="8" type={show?'text':'password'} autoComplete="current-password" className="w-full text-xs outline-none" placeholder="อย่างน้อย 8 ตัวอักษร"/><button type="button" onClick={()=>setShow(!show)} className="text-[#718594]">{show?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></label></div>
  {error&&<p className="mt-3 rounded-xl bg-[#fff0ee] px-3 py-2 text-[10px] text-[#bd493f]">{error}</p>}<button disabled={loading} className="mt-6 w-full rounded-xl bg-[#173653] py-3 text-xs font-semibold text-white shadow-[0_3px_0_#0e263b] disabled:opacity-60">{loading?'กำลังตรวจสอบ...':'เข้าสู่ระบบ'}</button><div className="mt-5 flex items-center gap-2 rounded-xl bg-[#f5f8fa] p-3"><KeyRound size={15} className="text-[#4c7896]"/><p className="text-[9px] leading-4 text-[#708390]">รหัสผ่าน LDAP จะถูกส่งเพื่อตรวจสอบครั้งเดียวและไม่จัดเก็บในระบบหอพัก</p></div></form></main></div>
}
export default Login
