import { useEffect, useMemo, useState } from 'react'
import { api } from '../../services/api'
import { Building2, ChevronRight, FileText, LoaderCircle, MapPin, Pencil, Plus, Search, ShieldCheck, Upload, UserRound, Users, X } from 'lucide-react'

const empty={tenantCode:'',tenantType:'student',tenantTypeCode:'STUDENT',title:'',firstName:'',lastName:'',nationalId:'',email:'',phone:'',currentAddress:'',faculty:'',department:'',program:'',major:'',organization:'',lineId:'',guardianName:'',guardianPhone:'',guardianEmail:'',guardianLineId:'',emergencyContactName:'',emergencyContactPhone:'',emergencyContactRelation:''}
const fieldClass='h-10 w-full rounded-xl border border-[#d7e1e7] bg-white px-3 text-xs outline-none focus:border-[#4c8fc8] focus:ring-2 focus:ring-[#4c8fc8]/15'

function Tenants({notify}){
  const [tenants,setTenants]=useState([]),[query,setQuery]=useState(''),[type,setType]=useState('all'),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false)
  const [options,setOptions]=useState({tenantTypes:[],titles:[],faculties:[],majors:[]})
  const [selected,setSelected]=useState(null),[editor,setEditor]=useState(null),[form,setForm]=useState(empty)
  const load=async()=>{setLoading(true);try{const [tenantRows,masterOptions]=await Promise.all([api('/tenants'),api('/tenants/options')]);setTenants(tenantRows);setOptions(masterOptions)}catch(error){notify(error.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  const rows=useMemo(()=>tenants.filter(x=>(type==='all'||x.tenant_type_code===type)&&`${x.tenant_code}${x.first_name}${x.last_name}${x.national_id||''}`.toLowerCase().includes(query.toLowerCase())),[tenants,type,query])
  const openEditor=tenant=>{setEditor(tenant||{});setForm(tenant?Object.fromEntries(Object.keys(empty).map(key=>[key,tenant[camelToSnake(key)]??tenant[key]??''])):empty)}
  const save=async event=>{event.preventDefault();setSaving(true);try{const body=Object.fromEntries(Object.entries(form).filter(([,value])=>value!==''));const options={method:editor?.id?'PATCH':'POST',body};await api(editor?.id?`/tenants/${editor.id}`:'/tenants',options);notify(editor?.id?'แก้ไขทะเบียนผู้เช่าแล้ว':'เพิ่มทะเบียนผู้เช่าแล้ว');setEditor(null);await load()}catch(error){notify(error.message)}finally{setSaving(false)}}
  const uploadCertificate=async event=>{const file=event.target.files?.[0];if(!file||!selected)return;try{const base64=await toBase64(file);await api(`/tenants/${selected.id}/documents`,{method:'POST',body:{documentType:'company_certificate',filename:file.name,mimeType:file.type,base64}});notify('จัดเก็บหนังสือรับรองบริษัทแล้ว')}catch(error){notify(error.message)}}
  const counts=Object.fromEntries(['student','staff','external'].map(key=>[key,tenants.filter(x=>x.tenant_type===key).length]))
  return <div className="enter-up space-y-5"><section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="flex items-center gap-2 text-[10px] font-semibold text-[#397caf]"><Users size={13}/> ทะเบียนผู้เช่าครบชุด 4.5.1</div><h2 className="mt-1 text-[25px] font-semibold text-[#152c46]">ข้อมูลคน ห้อง และสัญญา อยู่ในทะเบียนเดียว</h2><p className="mt-1 text-xs text-[#748594]">แสดงฟิลด์เฉพาะสำหรับนักศึกษา บุคลากร และบุคคลภายนอก</p></div><button onClick={()=>openEditor()} className="flex items-center justify-center gap-2 rounded-xl bg-[#f5bf3c] px-4 py-2.5 text-xs font-semibold text-[#173653] shadow-[0_3px_0_#c28d15]"><Plus size={16}/> เพิ่มผู้เช่า</button></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="ผู้เช่าทั้งหมด" value={tenants.length} tone="bg-[#edf5fb] text-[#397caf]"/><Stat label="นักศึกษา" value={counts.student} tone="bg-[#edf7f4] text-[#2f7d68]"/><Stat label="บุคลากร" value={counts.staff} tone="bg-[#fff7e4] text-[#ad7210]"/><Stat label="บุคคลภายนอก" value={counts.external} tone="bg-[#f4eff9] text-[#7c619e]"/></section>
    <section className="overflow-hidden rounded-2xl border border-[#dfe7eb] bg-white"><div className="flex flex-col gap-3 border-b border-[#e4eaee] p-4 md:flex-row md:items-center"><div><h3 className="text-sm font-semibold">รายชื่อผู้เช่า</h3><p className="text-[10px] text-[#82919d]">ข้อมูลติดต่อ ห้องพัก และสถานะสัญญาปัจจุบัน</p></div><div className="flex gap-2 md:ml-auto"><label className="flex h-9 items-center gap-2 rounded-xl border border-[#d8e2e7] bg-[#f9fbfc] px-3"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-44 bg-transparent text-[11px] outline-none" placeholder="ชื่อ รหัส หรือเลขบัตร"/></label><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border border-[#d8e2e7] px-3 text-[11px]"><option value="all">ทุกประเภท</option>{options.tenantTypes.map(item=><option key={item.id} value={item.code}>{item.name}</option>)}</select></div></div>
      {loading?<div className="grid min-h-80 place-items-center"><LoaderCircle className="animate-spin text-[#397caf]"/></div>:<div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left"><thead className="bg-[#f8fafb] text-[10px] text-[#728493]"><tr>{['ผู้เช่า','ประเภท','ข้อมูลติดต่อ','ห้องพัก','สัญญาปัจจุบัน',''].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-[#edf1f3]">{rows.map(row=><tr key={row.id} className="text-xs hover:bg-[#fafcfd]"><td className="px-4 py-3.5"><p className="font-medium text-[#294259]">{row.title}{row.first_name} {row.last_name}</p><p className="mt-1 font-['IBM_Plex_Sans'] text-[10px] text-[#81909c]">{row.tenant_code} · {maskId(row.national_id)}</p></td><td className="px-4 py-3.5"><span className="rounded-full bg-[#eef4f7] px-2.5 py-1 text-[10px] text-[#526d82]">{row.tenant_type_name}</span></td><td className="px-4 py-3.5 text-[10px] text-[#5f7485]">{row.phone||'-'}<p className="mt-1">{row.email||'-'}</p></td><td className="px-4 py-3.5"><span className="flex items-center gap-1 text-[10px] text-[#5f7485]"><Building2 size={12}/>{row.building_name||'-'} · {row.room_no||'-'} · {row.bed_no||'-'}</span></td><td className="px-4 py-3.5"><p className="text-[10px] font-medium">{row.contract_no||'ยังไม่มีสัญญา'}</p>{row.contract_no&&<p className="mt-1 text-[9px] text-[#81909c]">{row.contract_starts_at} → {row.contract_ends_at}</p>}</td><td className="px-4 py-3.5"><button onClick={()=>setSelected(row)} className="grid size-8 place-items-center rounded-lg hover:bg-[#edf4f7]"><ChevronRight size={15}/></button></td></tr>)}</tbody></table></div>}</section>
    {selected&&<TenantDetail tenant={selected} close={()=>setSelected(null)} edit={()=>{openEditor(selected);setSelected(null)}} uploadCertificate={uploadCertificate}/>}
    {editor&&<TenantForm form={form} setForm={setForm} options={options} editing={Boolean(editor.id)} save={save} close={()=>setEditor(null)} saving={saving}/>}
  </div>
}

function TenantDetail({tenant,close,edit,uploadCertificate}){return <div className="fixed inset-0 z-50 grid place-items-end bg-[#142a46]/40 sm:place-items-center sm:p-4" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-t-3xl bg-white p-6 sm:rounded-3xl"><div className="flex justify-between"><div><p className="text-[10px] text-[#718493]">{tenant.tenant_type_name||typeText(tenant.tenant_type)} · {tenant.tenant_code}</p><h3 className="mt-1 text-xl font-semibold">{tenant.title}{tenant.first_name} {tenant.last_name}</h3></div><button onClick={close} className="grid size-9 place-items-center rounded-full bg-[#f1f4f6]"><X size={17}/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Info icon={MapPin} label="ที่อยู่ปัจจุบัน" value={tenant.current_address}/><Info icon={ShieldCheck} label="เลขบัตรประชาชน" value={tenant.national_id}/><Info icon={UserRound} label="ติดต่อผู้เช่า" value={[tenant.phone,tenant.email,tenant.line_id].filter(Boolean).join(' / ')}/><Info icon={Building2} label="ห้องและสัญญา" value={`${tenant.building_name||'-'} · ${tenant.room_no||'-'} · ${tenant.contract_no||'ยังไม่มีสัญญา'}`}/>{tenant.tenant_type==='student'?<><Info label="การศึกษา" value={[tenant.faculty,tenant.program,tenant.major].filter(Boolean).join(' / ')}/><Info label="ผู้ปกครอง" value={[tenant.guardian_name,tenant.guardian_phone,tenant.guardian_email,tenant.guardian_line_id].filter(Boolean).join(' / ')}/></>:<><Info label="หน่วยงาน" value={tenant.organization||tenant.department}/><Info label="บุคคลติดต่อได้" value={[tenant.emergency_contact_name,tenant.emergency_contact_phone,tenant.emergency_contact_relation].filter(Boolean).join(' / ')}/></>}</div><div className="mt-5 flex flex-wrap gap-2"><button onClick={edit} className="flex items-center gap-2 rounded-xl bg-[#173653] px-4 py-2.5 text-xs text-white"><Pencil size={14}/> แก้ไขทะเบียน</button>{tenant.tenant_type==='external'&&<label className="flex cursor-pointer items-center gap-2 rounded-xl border border-[#d8e2e7] px-4 py-2.5 text-xs"><Upload size={14}/> แนบหนังสือรับรองบริษัท<input type="file" accept="application/pdf,image/jpeg,image/png" onChange={uploadCertificate} className="hidden"/></label>}</div></div></div>}

function TenantForm({form,setForm,options,editing,save,close,saving}){
  const update=(key,value)=>setForm(x=>({...x,[key]:value}))
  const selectedFaculty=options.faculties.find(item=>item.name===form.faculty)
  const majors=selectedFaculty?options.majors.filter(item=>item.parent_id===selectedFaculty.id):options.majors
  const selectTenantType=code=>{const item=options.tenantTypes.find(option=>option.code===code);setForm(x=>({...x,tenantTypeCode:code,tenantType:item?.system_type||'external'}))}
  return <div className="fixed inset-0 z-50 grid place-items-end bg-[#142a46]/40 sm:place-items-center sm:p-4" onMouseDown={e=>e.target===e.currentTarget&&close()}><form onSubmit={save} className="max-h-[94vh] w-full max-w-4xl overflow-y-auto rounded-t-3xl bg-white p-6 sm:rounded-3xl"><div className="flex justify-between"><div><p className="text-[10px] font-semibold text-[#397caf]">ทะเบียนผู้เช่า</p><h3 className="mt-1 text-xl font-semibold">{editing?'แก้ไขข้อมูลผู้เช่า':'เพิ่มผู้เช่าใหม่'}</h3></div><button type="button" onClick={close} className="grid size-9 place-items-center rounded-full bg-[#f1f4f6]"><X size={17}/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
    <Field label="ประเภทผู้เช่า"><select required value={form.tenantTypeCode} onChange={e=>selectTenantType(e.target.value)} className={fieldClass}>{form.tenantTypeCode&&!options.tenantTypes.some(item=>item.code===form.tenantTypeCode)&&<option value={form.tenantTypeCode}>{typeText(form.tenantType)}</option>}{options.tenantTypes.map(item=><option key={item.id} value={item.code}>{item.name}</option>)}</select></Field>
    <Field label={form.tenantType==='student'?'รหัสนักศึกษา':'รหัสผู้เช่า'}><input required value={form.tenantCode} onChange={e=>update('tenantCode',e.target.value)} className={fieldClass}/></Field>
    <Field label="คำนำหน้าชื่อ"><select value={form.title} onChange={e=>update('title',e.target.value)} className={fieldClass}><option value="">ไม่ระบุ</option>{form.title&&!options.titles.some(item=>item.name===form.title)&&<option value={form.title}>{form.title}</option>}{options.titles.map(item=><option key={item.id} value={item.name}>{item.name}</option>)}</select></Field>
    <Field label="ชื่อ"><input required value={form.firstName} onChange={e=>update('firstName',e.target.value)} className={fieldClass}/></Field><Field label="นามสกุล"><input required value={form.lastName} onChange={e=>update('lastName',e.target.value)} className={fieldClass}/></Field><Field label="เลขบัตรประชาชน"><input value={form.nationalId} onChange={e=>update('nationalId',e.target.value)} className={fieldClass}/></Field><Field label="โทรศัพท์"><input value={form.phone} onChange={e=>update('phone',e.target.value)} className={fieldClass}/></Field><Field label="E-mail"><input type="email" value={form.email} onChange={e=>update('email',e.target.value)} className={fieldClass}/></Field><Field label="LINE ID"><input value={form.lineId} onChange={e=>update('lineId',e.target.value)} className={fieldClass}/></Field><Field label="ที่อยู่ปัจจุบัน" wide><textarea value={form.currentAddress} onChange={e=>update('currentAddress',e.target.value)} className={`${fieldClass} h-20 py-3`}/></Field>
    {form.tenantType==='student'?<><Field label="คณะ"><select value={form.faculty} onChange={e=>setForm(x=>({...x,faculty:e.target.value,major:''}))} className={fieldClass}><option value="">เลือกคณะ / โรงเรียน</option>{form.faculty&&!options.faculties.some(item=>item.name===form.faculty)&&<option value={form.faculty}>{form.faculty}</option>}{options.faculties.map(item=><option key={item.id} value={item.name}>{item.name}</option>)}</select></Field><Field label="หลักสูตร"><input value={form.program} onChange={e=>update('program',e.target.value)} className={fieldClass}/></Field><Field label="สาขาวิชา"><select value={form.major} onChange={e=>update('major',e.target.value)} className={fieldClass}><option value="">เลือกสาขาวิชา</option>{form.major&&!majors.some(item=>item.name===form.major)&&<option value={form.major}>{form.major}</option>}{majors.map(item=><option key={item.id} value={item.name}>{item.name}</option>)}</select></Field><Field label="ชื่อผู้ปกครอง"><input value={form.guardianName} onChange={e=>update('guardianName',e.target.value)} className={fieldClass}/></Field><Field label="โทรศัพท์ผู้ปกครอง"><input value={form.guardianPhone} onChange={e=>update('guardianPhone',e.target.value)} className={fieldClass}/></Field><Field label="E-mail ผู้ปกครอง"><input type="email" value={form.guardianEmail} onChange={e=>update('guardianEmail',e.target.value)} className={fieldClass}/></Field><Field label="LINE ID ผู้ปกครอง"><input value={form.guardianLineId} onChange={e=>update('guardianLineId',e.target.value)} className={fieldClass}/></Field></>:<><Field label="หน่วยงาน"><input value={form.organization} onChange={e=>update('organization',e.target.value)} className={fieldClass}/></Field><Field label="ชื่อบุคคลที่ติดต่อได้"><input value={form.emergencyContactName} onChange={e=>update('emergencyContactName',e.target.value)} className={fieldClass}/></Field><Field label="โทรศัพท์บุคคลที่ติดต่อได้"><input value={form.emergencyContactPhone} onChange={e=>update('emergencyContactPhone',e.target.value)} className={fieldClass}/></Field><Field label="ความสัมพันธ์"><input value={form.emergencyContactRelation} onChange={e=>update('emergencyContactRelation',e.target.value)} className={fieldClass}/></Field></>}
  </div><button disabled={saving} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#f5bf3c] py-3 text-xs font-semibold text-[#173653]">{saving&&<LoaderCircle size={14} className="animate-spin"/>} บันทึกทะเบียนผู้เช่า</button></form></div>
}

function Stat({label,value,tone}){return <div className="rounded-2xl border border-[#dfe7eb] bg-white p-4"><p className="text-[10px] text-[#748694]">{label}</p><div className="mt-2 flex items-center justify-between"><p className="text-xl font-semibold">{value} <span className="text-[9px] font-normal">คน</span></p><div className={`grid size-8 place-items-center rounded-lg ${tone}`}><UserRound size={15}/></div></div></div>}
function Info({icon:Icon=FileText,label,value}){return <div className="rounded-xl bg-[#f5f8fa] p-3"><p className="flex items-center gap-1 text-[10px] text-[#7e8e9a]"><Icon size={12}/>{label}</p><p className="mt-1 text-xs leading-5">{value||'-'}</p></div>}
function Field({label,wide,children}){return <label className={wide?'sm:col-span-2 lg:col-span-3':''}><span className="mb-1.5 block text-[10px] font-medium text-[#657a8b]">{label}</span>{children}</label>}
function typeText(value){return({student:'นักศึกษา',staff:'บุคลากร',external:'บุคคลภายนอก'})[value]||value}
function maskId(value){return value?`${value.slice(0,3)}••••••${value.slice(-3)}`:'ไม่ระบุเลขบัตร'}
function camelToSnake(value){return value.replace(/[A-Z]/g,letter=>`_${letter.toLowerCase()}`)}
function toBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)})}
export default Tenants
