import { useEffect, useMemo, useState } from 'react'
import {
  BedDouble, Bell, Building2, CalendarDays, CheckCircle2, ChevronRight, Download,
  FileSignature, FileText, History, Home, LoaderCircle, LogOut, Paperclip,
  MessageCircle, Newspaper, ReceiptText, RefreshCw, Send, ShieldCheck, Upload, WalletCards, Wrench,
} from 'lucide-react'
import { api, downloadApiFile, fileToBase64 } from '../../services/api'

const tabs = [
  ['debts','หนี้ของฉัน',WalletCards],
  ['proof','ส่งหลักฐาน',Upload],
  ['lease','การเช่าของฉัน',FileSignature],
  ['repair','แจ้งซ่อม',Wrench],
  ['news','ข่าวสาร',Newspaper],
]
const fieldClass='h-11 w-full rounded-xl border border-[#d5e1e7] bg-white px-3 text-xs outline-none transition focus:border-[#4c8fc8] focus:ring-2 focus:ring-[#4c8fc8]/15'
const invoiceLabels={issued:'รอชำระ',partial:'ชำระบางส่วน',paid:'ชำระแล้ว',cancelled:'ยกเลิก'}
const proofLabels={pending:'รอตรวจสอบ',approved:'ตรวจสอบแล้ว',rejected:'ไม่ผ่าน',cancelled:'ยกเลิก'}
const repairLabels={waiting:'รอเข้าซ่อม',repairing:'ระหว่างซ่อม',waiting_parts:'รออะไหล่',completed:'ซ่อมเรียบร้อย',closed:'ปิดงาน'}

function TenantPortal({user,onLogout}){
  const [tab,setTab]=useState('debts')
  const [data,setData]=useState({summary:null,invoices:[],proofs:[],receipts:[],contracts:[],repairs:[],announcements:[]})
  const [loading,setLoading]=useState(true)
  const [saving,setSaving]=useState(false)
  const [notice,setNotice]=useState('')
  const [proofInvoiceId,setProofInvoiceId]=useState('')

  const load=async()=>{setLoading(true);try{const [summary,invoices,proofs,receipts,contracts,repairs,announcements]=await Promise.all([api('/tenant-portal/summary'),api('/invoices'),api('/payment-proofs'),api('/receipts'),api('/contracts'),api('/repairs'),api('/announcements')]);setData({summary,invoices,proofs,receipts,contracts,repairs,announcements})}catch(error){show(error.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  const show=message=>{setNotice(message);setTimeout(()=>setNotice(''),3500)}
  const outstanding=useMemo(()=>data.invoices.filter(x=>['issued','partial'].includes(x.status)),[data.invoices])
  const run=async(action,message)=>{setSaving(true);try{await action();show(message);await load()}catch(error){show(error.message)}finally{setSaving(false)}}

  return <div className="min-h-screen bg-[#eef4f7] text-[#172b45]">
    <header className="border-b border-[#d9e4e9] bg-[#142a46] text-white"><div className="mx-auto flex h-[72px] max-w-6xl items-center gap-3 px-4 sm:px-6"><div className="grid size-10 place-items-center rounded-xl bg-[#f5bf3c] text-[#142a46]"><Building2 size={21}/></div><div><p className="font-['IBM_Plex_Sans'] text-sm font-semibold">CAMPUS NEST</p><p className="text-[9px] text-[#9fb2c3]">Resident Portal</p></div><div className="ml-auto flex items-center gap-2"><button onClick={()=>setTab('news')} title="ข่าวสาร" className="relative grid size-9 place-items-center rounded-full border border-white/10 text-[#b8c8d5] hover:bg-white/10"><Bell size={16}/>{data.announcements.length>0&&<i className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-[#f5bf3c]"/>}</button><div className="hidden text-right sm:block"><p className="text-xs font-medium">{user.display_name}</p><p className="text-[9px] text-[#9fb2c3]">{tenantType(data.summary?.tenant_type)}</p></div><button onClick={onLogout} title="ออกจากระบบ" className="grid size-9 place-items-center rounded-full border border-white/10 text-[#b8c8d5] hover:bg-white/10"><LogOut size={16}/></button></div></div></header>

    <main className="mx-auto max-w-6xl px-4 py-6 sm:px-6 sm:py-8">
      <section className="grid gap-5 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="flex items-center gap-2 text-[10px] font-semibold text-[#397caf]"><Home size={12}/> พื้นที่ของผู้พัก · ข้อ 4.6</p><h1 className="mt-2 text-2xl font-semibold tracking-[-.02em] sm:text-3xl">สวัสดี, {data.summary?.first_name||user.display_name}</h1><p className="mt-2 text-xs text-[#718493]">ตรวจเอกสาร ชำระหนี้ และติดตามเรื่องห้องพักของคุณได้จากที่นี่</p></div><button onClick={load} disabled={loading} className="inline-flex w-fit items-center gap-2 rounded-xl border border-[#cedce3] bg-white px-3 py-2 text-[10px] font-medium text-[#506b7e]"><RefreshCw size={13} className={loading?'animate-spin':''}/> อัปเดตข้อมูล</button></section>

      <OccupancyRail summary={data.summary}/>

      <nav className="mt-6 grid grid-cols-2 gap-2 rounded-2xl border border-[#dae5ea] bg-white p-2 shadow-[0_3px_18px_rgba(26,55,80,.04)] sm:grid-cols-5">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`flex items-center gap-2 rounded-xl px-3 py-3 text-left text-[11px] font-medium transition ${tab===id?'bg-[#142a46] text-white shadow-sm':'text-[#607688] hover:bg-[#f1f6f8]'}`}><span className={`grid size-8 place-items-center rounded-lg ${tab===id?'bg-white/10':'bg-[#eaf4fa] text-[#397caf]'}`}><Icon size={15}/></span>{label}</button>)}</nav>

      <section className="mt-4 min-h-[360px] rounded-2xl border border-[#dae5ea] bg-white p-4 shadow-[0_4px_22px_rgba(26,55,80,.04)] sm:p-6">
        {loading?<Loading/>:<>
          {tab==='debts'&&<DebtPanel invoices={data.invoices} receipts={data.receipts} onProof={invoice=>{setProofInvoiceId(String(invoice.id));setTab('proof')}}/>}
          {tab==='proof'&&<ProofPanel invoices={outstanding} selectedInvoiceId={proofInvoiceId} proofs={data.proofs} saving={saving} submit={payload=>run(()=>submitProof(payload),'ส่งหลักฐานแล้ว เจ้าหน้าที่จะตรวจสอบและออกใบเสร็จให้คุณ')}/>}
          {tab==='lease'&&<LeasePanel contracts={data.contracts}/>}
          {tab==='repair'&&<RepairPanel summary={data.summary} repairs={data.repairs} saving={saving} submit={payload=>run(()=>api('/repairs',{method:'POST',body:payload}),'รับเรื่องแจ้งซ่อมแล้ว คุณติดตามสถานะได้ในหน้านี้')}/>}
          {tab==='news'&&<NewsPanel announcements={data.announcements} notify={show}/>}
        </>}
      </section>
    </main>
    {notice&&<div role="status" className="fixed bottom-5 left-1/2 z-50 flex -translate-x-1/2 items-center gap-2 rounded-xl bg-[#142a46] px-4 py-3 text-xs text-white shadow-xl"><CheckCircle2 size={15} className="text-[#f5bf3c]"/>{notice}</div>}
  </div>
}

async function submitProof(payload){const file=payload.file;if(!file)throw new Error('กรุณาเลือกไฟล์หลักฐาน');if(file.size>3_000_000)throw new Error('ไฟล์หลักฐานต้องไม่เกิน 3 MB');const fileBase64=await fileToBase64(file);return api('/payment-proofs',{method:'POST',body:{invoiceId:Number(payload.invoiceId),amount:Number(payload.amount),referenceNo:payload.referenceNo||undefined,paidAt:new Date(payload.paidAt).toISOString(),filename:file.name,mimeType:file.type,fileBase64}})}

function OccupancyRail({summary}){return <section className="mt-6 overflow-hidden rounded-2xl border border-[#d8e4e9] bg-white"><div className="grid sm:grid-cols-3"><Rail icon={BedDouble} label="ห้องพักปัจจุบัน" value={summary?.room_no?`${summary.building_name} · ห้อง ${summary.room_no} · เตียง ${summary.bed_no}`:'ยังไม่มีห้องพัก'}/><Rail icon={FileText} label="สัญญาปัจจุบัน" value={summary?.contract_no?`${summary.contract_no} · ถึง ${date(summary.contract_ends_at)}`:'ยังไม่มีสัญญาที่ใช้งาน'}/><Rail icon={WalletCards} label="ยอดที่ต้องชำระ" value={`${money(summary?.outstanding_balance)} บาท`} accent={Number(summary?.outstanding_balance)>0}/></div></section>}
function Rail({icon:Icon,label,value,accent}) {return <div className="relative flex items-center gap-3 border-b border-[#e5ecef] p-4 last:border-0 sm:border-b-0 sm:border-r"><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${accent?'bg-[#fff3df] text-[#a86f08]':'bg-[#eaf4fa] text-[#397caf]'}`}><Icon size={18}/></span><span><small className="block text-[9px] text-[#7b8d9a]">{label}</small><b className="mt-1 block text-[11px] font-semibold text-[#29445a]">{value}</b></span></div>}

function DebtPanel({invoices,receipts,onProof}){return <div className="space-y-6"><SectionTitle icon={WalletCards} title="หนี้และใบแจ้งหนี้ของฉัน" detail="แสดงเฉพาะรายการที่ผูกกับบัญชีของคุณ"/><div className="grid gap-3">{invoices.map(x=><article key={x.id} className="grid gap-3 rounded-2xl border border-[#dfe8ec] p-4 md:grid-cols-[1fr_auto] md:items-center"><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#edf5fb] text-[#397caf]"><ReceiptText size={17}/></span><div><div className="flex flex-wrap items-center gap-2"><b className="font-['IBM_Plex_Sans'] text-xs">{x.invoice_no}</b><Status text={invoiceLabels[x.status]} tone={x.status==='paid'?'green':x.status==='cancelled'?'gray':'yellow'}/></div><p className="mt-1 text-[10px] text-[#718493]">{x.item_summary||'รายการค่าใช้จ่ายหอพัก'} · กำหนด {date(x.due_date)}</p><p className="mt-2 text-sm font-semibold">คงเหลือ {money(x.balance)} บาท <small className="font-normal text-[#81919d]">จาก {money(x.total)} บาท</small></p></div></div><div className="flex gap-2 md:justify-end"><button onClick={()=>downloadApiFile(`/invoices/${x.id}/document`,`${x.invoice_no}.pdf`)} className="portal-secondary"><Download size={13}/> ดาวน์โหลด</button>{['issued','partial'].includes(x.status)&&<button onClick={()=>onProof(x)} className="portal-primary"><Upload size={13}/> ส่งหลักฐาน</button>}</div></article>)}{invoices.length===0&&<Empty icon={ShieldCheck} title="ยังไม่มีรายการหนี้" detail="เมื่อมีใบแจ้งหนี้ รายการจะปรากฏที่นี่"/>}</div><div><h3 className="mb-3 text-xs font-semibold">ใบเสร็จล่าสุด</h3><div className="divide-y divide-[#e8eef1] rounded-xl border border-[#e0e8ec]">{receipts.map(x=><div key={x.id} className="flex flex-wrap items-center gap-3 p-3"><span className="grid size-8 place-items-center rounded-lg bg-[#edf7f4] text-[#26715e]"><CheckCircle2 size={14}/></span><div className="flex-1"><b className="block font-['IBM_Plex_Sans'] text-[11px]">{x.receipt_no}</b><small className="text-[9px] text-[#7f909c]">{dateTime(x.paid_at)} · {x.invoice_no}</small></div><b className="text-xs">{money(x.amount)} บาท</b><button title="ดาวน์โหลดใบเสร็จ" onClick={()=>downloadApiFile(`/receipts/${x.id}/document`,`${x.receipt_no}.pdf`)} className="icon-button"><Download size={14}/></button></div>)}{receipts.length===0&&<p className="p-5 text-center text-[10px] text-[#84939e]">ยังไม่มีใบเสร็จรับเงิน</p>}</div></div></div>}

function ProofPanel({invoices,selectedInvoiceId,proofs,saving,submit}){const handle=e=>{e.preventDefault();submit(Object.fromEntries(new FormData(e.currentTarget)))};return <div className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><form onSubmit={handle} className="rounded-2xl bg-[#f3f8fb] p-5"><SectionTitle icon={Upload} title="ส่งหลักฐานการชำระ" detail="รองรับ JPG, PNG หรือ PDF ไม่เกิน 3 MB"/><div className="mt-5 grid gap-4"><Field label="ใบแจ้งหนี้"><select key={selectedInvoiceId} required name="invoiceId" defaultValue={selectedInvoiceId} className={fieldClass}><option value="">เลือกใบแจ้งหนี้</option>{invoices.map(x=><option key={x.id} value={x.id}>{x.invoice_no} · คงเหลือ {money(x.balance)} บาท</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="จำนวนเงิน"><input required type="number" min="0.01" step="0.01" name="amount" className={fieldClass}/></Field><Field label="วันเวลาที่โอน"><input required type="datetime-local" name="paidAt" className={fieldClass}/></Field></div><Field label="เลขอ้างอิง"><input name="referenceNo" className={fieldClass} placeholder="เช่น KPLUS-123456"/></Field><Field label="ไฟล์หลักฐาน"><input required type="file" name="file" accept="image/jpeg,image/png,application/pdf" className={`${fieldClass} h-auto py-2`}/></Field><button disabled={saving||invoices.length===0} className="portal-primary h-11 justify-center disabled:opacity-50">{saving?<LoaderCircle size={15} className="animate-spin"/>:<Send size={15}/>} ส่งให้เจ้าหน้าที่ตรวจสอบ</button>{invoices.length===0&&<p className="text-center text-[10px] text-[#748694]">ไม่มีใบแจ้งหนี้ที่รอชำระ</p>}</div></form><div><SectionTitle icon={History} title="ประวัติหลักฐาน" detail="ติดตามผลการตรวจสอบจากเจ้าหน้าที่"/><div className="mt-4 space-y-2">{proofs.map(x=><div key={x.id} className="flex items-center gap-3 rounded-xl border border-[#e0e8ec] p-3"><span className="grid size-9 place-items-center rounded-lg bg-[#edf5fb] text-[#397caf]"><Paperclip size={15}/></span><div className="min-w-0 flex-1"><b className="block truncate text-[11px]">{x.filename}</b><small className="text-[9px] text-[#7f909c]">{x.invoice_no} · {dateTime(x.paid_at)}</small>{x.review_note&&<p className="mt-1 text-[9px] text-[#63798a]">{x.review_note}</p>}</div><div className="text-right"><b className="block text-[11px]">{money(x.amount)} บาท</b><Status text={proofLabels[x.status]} tone={x.status==='approved'?'green':x.status==='rejected'?'red':'yellow'}/></div></div>)}{proofs.length===0&&<Empty icon={Paperclip} title="ยังไม่มีหลักฐาน" detail="หลักฐานที่ส่งแล้วจะปรากฏพร้อมสถานะที่นี่"/>}</div></div></div>}

function LeasePanel({contracts}){return <div><SectionTitle icon={FileSignature} title="ข้อมูลการเช่าของฉัน" detail="ดูรายละเอียดและดาวน์โหลดสัญญาที่ผูกกับบัญชีของคุณ"/><div className="mt-5 grid gap-4 lg:grid-cols-2">{contracts.map(x=><article key={x.id} className="overflow-hidden rounded-2xl border border-[#dce6eb]"><div className="flex items-start justify-between bg-[#142a46] p-4 text-white"><div><small className="text-[9px] text-[#9fb2c3]">เลขที่สัญญา</small><h3 className="mt-1 font-['IBM_Plex_Sans'] text-sm font-semibold">{x.contract_no}</h3></div><Status text={contractStatus(x.document_status)} tone={x.document_status==='signed'?'green':'yellow'}/></div><div className="grid gap-3 p-4 text-[10px]"><Info icon={Building2} label="สถานที่พัก" value={`${x.building_name||'-'} · ห้อง ${x.room_no||'-'} · เตียง ${x.bed_no||'-'}`}/><Info icon={CalendarDays} label="ระยะเวลาสัญญา" value={`${date(x.starts_at)} – ${date(x.ends_at)}`}/><Info icon={ReceiptText} label="ประเภทสัญญา" value={`${x.contract_type} · ${period(x.rental_period)}`}/><button onClick={()=>downloadApiFile(`/contracts/${x.id}/document`,`${x.contract_no}.pdf`)} className="portal-secondary mt-1 justify-center"><Download size={13}/> ดาวน์โหลดสัญญา PDF</button></div></article>)}{contracts.length===0&&<div className="lg:col-span-2"><Empty icon={FileSignature} title="ยังไม่มีสัญญาเช่า" detail="ติดต่อเจ้าหน้าที่หอพักหากคุณเข้าพักแล้วแต่ยังไม่พบสัญญา"/></div>}</div></div>}

function RepairPanel({summary,repairs,saving,submit}){const handle=e=>{e.preventDefault();const form=Object.fromEntries(new FormData(e.currentTarget));submit({title:form.title,detail:form.detail,priority:form.priority,roomId:summary?.room_id||null})};return <div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><form onSubmit={handle} className="rounded-2xl bg-[#f3f8fb] p-5"><SectionTitle icon={Wrench} title="แจ้งซ่อมห้องพัก" detail={summary?.room_no?`ระบบจะผูกเรื่องกับห้อง ${summary.room_no} อัตโนมัติ`:'แจ้งเรื่องได้โดยเจ้าหน้าที่จะตรวจสอบข้อมูลห้องอีกครั้ง'}/><div className="mt-5 grid gap-4"><Field label="เรื่องที่ต้องการแจ้ง"><input required name="title" className={fieldClass} placeholder="เช่น หลอดไฟไม่ทำงาน"/></Field><Field label="รายละเอียด"><textarea required name="detail" rows="4" className={`${fieldClass} h-auto py-3`} placeholder="ระบุตำแหน่งและอาการให้ชัดเจน"/></Field><Field label="ความเร่งด่วน"><select name="priority" className={fieldClass}><option value="normal">ปกติ</option><option value="high">เร่งด่วน</option><option value="urgent">ฉุกเฉิน</option><option value="low">ไม่เร่งด่วน</option></select></Field><button disabled={saving} className="portal-primary h-11 justify-center">{saving?<LoaderCircle size={15} className="animate-spin"/>:<Send size={15}/>} ส่งเรื่องแจ้งซ่อม</button></div></form><div><SectionTitle icon={History} title="งานซ่อมของฉัน" detail="ติดตามสถานะและวันที่แก้ไขล่าสุด"/><div className="mt-4 space-y-3">{repairs.map(x=><article key={x.id} className="rounded-xl border border-[#e0e8ec] p-4"><div className="flex items-start gap-3"><span className="grid size-9 place-items-center rounded-lg bg-[#fff5df] text-[#a86f08]"><Wrench size={15}/></span><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-xs">{x.title}</b><Status text={repairLabels[x.workflow_status]||x.workflow_status} tone={['completed','closed'].includes(x.workflow_status)?'green':'yellow'}/></div><p className="mt-1 text-[10px] leading-5 text-[#6f8291]">{x.detail||'ไม่ระบุรายละเอียด'}</p><p className="mt-2 text-[9px] text-[#8997a2]">{x.building_name||'ข้อมูลห้องรอตรวจสอบ'} {x.room_no&&`· ห้อง ${x.room_no}`} · แจ้งเมื่อ {dateTime(x.created_at)}</p></div><ChevronRight size={15} className="text-[#9ca9b2]"/></div></article>)}{repairs.length===0&&<Empty icon={Wrench} title="ยังไม่มีงานซ่อม" detail="เรื่องที่คุณแจ้งจะปรากฏและอัปเดตสถานะที่นี่"/>}</div></div></div>}

function NewsPanel({announcements,notify}){
  const [selected,setSelected]=useState(null),[comments,setComments]=useState([]),[sending,setSending]=useState(false)
  const open=async item=>{setSelected(item);try{setComments(await api(`/announcements/${item.id}/comments`))}catch(error){notify(error.message)}}
  const comment=async event=>{event.preventDefault();const body=new FormData(event.currentTarget).get('body');setSending(true);try{await api(`/announcements/${selected.id}/comments`,{method:'POST',body:{body}});event.currentTarget.reset();setComments(await api(`/announcements/${selected.id}/comments`));notify('ส่งความคิดเห็นแล้ว')}catch(error){notify(error.message)}finally{setSending(false)}}
  return <div><SectionTitle icon={Newspaper} title="ข่าวสารจากหอพัก" detail="ระบบแสดงเฉพาะข่าวส่วนกลางและข่าวที่ส่งถึงห้องของคุณ"/><div className="mt-5 grid gap-4 lg:grid-cols-[.9fr_1.1fr]"><div className="space-y-2">{announcements.map(item=><button key={item.id} onClick={()=>open(item)} className={`w-full rounded-xl border p-4 text-left transition ${selected?.id===item.id?'border-[#397caf] bg-[#f0f7fb]':'border-[#e0e8ec] hover:bg-[#f8fafb]'}`}><div className="flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-[#eaf4fa] text-[#397caf]"><Newspaper size={15}/></span><span className="min-w-0 flex-1"><b className="block text-xs text-[#29455a]">{item.title}</b><small className="mt-1 block text-[9px] text-[#82919c]">{item.audience_type==='all'?'ประกาศทุกห้อง':`เฉพาะห้อง ${item.room_no}`} · {dateTime(item.published_at)}</small><span className="mt-2 flex items-center gap-1 text-[9px] text-[#6d8393]"><MessageCircle size={11}/> {item.comment_count} ความคิดเห็น</span></span><ChevronRight size={14} className="text-[#9cabb4]"/></div></button>)}{announcements.length===0&&<Empty icon={Newspaper} title="ยังไม่มีข่าวสาร" detail="ข่าวจากเจ้าหน้าที่จะปรากฏที่นี่"/>}</div><div className="rounded-2xl bg-[#f3f8fb] p-5">{selected?<><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#397caf]">{selected.audience_type==='all'?'ถึงผู้เช่าทุกห้อง':`ถึงห้อง ${selected.room_no}`}</p><h3 className="mt-2 text-base font-semibold">{selected.title}</h3><p className="mt-3 whitespace-pre-line text-[10px] leading-6 text-[#5f7788]">{selected.body}</p><div className="my-4 border-t border-[#dce7eb]"/><h4 className="text-[10px] font-semibold">ความคิดเห็น</h4><div className="mt-3 space-y-2">{comments.map(item=><div key={item.id} className="rounded-xl bg-white p-3"><div className="flex justify-between gap-3"><b className="text-[9px] text-[#355267]">{item.tenant_name}</b><small className="text-[8px] text-[#92a0a9]">{dateTime(item.created_at)}</small></div><p className="mt-1 text-[10px] leading-5 text-[#617887]">{item.body}</p></div>)}{comments.length===0&&<p className="py-3 text-center text-[9px] text-[#8998a2]">ยังไม่มีความคิดเห็น</p>}</div>{selected.comments_enabled?<form onSubmit={comment} className="mt-3 flex gap-2"><input required name="body" maxLength="1000" className={`${fieldClass} flex-1`} placeholder="เขียนความคิดเห็น"/><button disabled={sending} className="portal-primary shrink-0 px-4">{sending?<LoaderCircle size={14} className="animate-spin"/>:<Send size={14}/>}</button></form>:<p className="mt-3 rounded-xl bg-white p-3 text-center text-[9px] text-[#87959f]">ประกาศนี้ปิดการแสดงความคิดเห็น</p>}</>:<div className="grid min-h-64 place-items-center text-center"><div><Newspaper size={28} className="mx-auto text-[#9aaab4]"/><b className="mt-3 block text-xs">เลือกข่าวที่ต้องการอ่าน</b><p className="mt-1 text-[9px] text-[#84949f]">รายละเอียดและความคิดเห็นจะแสดงที่นี่</p></div></div>}</div></div></div>
}

function SectionTitle({icon:Icon,title,detail}){return <div className="flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#eaf4fa] text-[#397caf]"><Icon size={16}/></span><div><h2 className="text-sm font-semibold">{title}</h2><p className="mt-1 text-[10px] text-[#788b99]">{detail}</p></div></div>}
function Field({label,children}){return <label><span className="mb-1.5 block text-[10px] font-medium text-[#617688]">{label}</span>{children}</label>}
function Status({text,tone='gray'}){const styles={green:'bg-[#e8f6f1] text-[#26715e]',yellow:'bg-[#fff4db] text-[#94610b]',red:'bg-[#fff0ee] text-[#b74e44]',gray:'bg-[#eff2f4] text-[#71808c]'};return <span className={`inline-block rounded-full px-2 py-1 text-[8px] font-medium ${styles[tone]}`}>{text||'-'}</span>}
function Info({icon:Icon,label,value}){return <div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-[#f0f5f7] text-[#5c7890]"><Icon size={14}/></span><div><small className="text-[#80909c]">{label}</small><p className="mt-0.5 font-medium text-[#314b61]">{value}</p></div></div>}
function Empty({icon:Icon,title,detail}){return <div className="grid min-h-36 place-items-center rounded-xl border border-dashed border-[#d6e2e8] p-5 text-center"><div><Icon size={24} className="mx-auto text-[#9aabb6]"/><b className="mt-3 block text-xs">{title}</b><p className="mt-1 text-[9px] text-[#83939e]">{detail}</p></div></div>}
function Loading(){return <div className="grid min-h-72 place-items-center"><LoaderCircle className="animate-spin text-[#397caf]"/></div>}
function money(value){return Number(value||0).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2})}
function date(value){return value?new Date(value).toLocaleDateString('th-TH',{dateStyle:'medium'}):'-'}
function dateTime(value){return value?new Date(value).toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'}):'-'}
function tenantType(value){return({student:'นักศึกษา',staff:'บุคลากร',external:'บุคคลภายนอก'})[value]||'ผู้พักอาศัย'}
function period(value){return({daily:'รายวัน',monthly:'รายเดือน',term:'รายภาคเรียน',yearly:'รายปี'})[value]||value}
function contractStatus(value){return({draft:'ฉบับร่าง',sent:'รอลงนาม',signed:'ลงนามแล้ว'})[value]||value}

export default TenantPortal
