import { useEffect, useMemo, useState } from 'react'
import {
  BadgeCheck, Banknote, Check, CircleDollarSign, Download, FileCheck2, FilePlus2,
  Landmark, LoaderCircle, Mail, Paperclip, ReceiptText, RefreshCw, Search, Send,
  ShieldCheck, Upload, X, XCircle,
} from 'lucide-react'
import FinanceTabs from '../../components/FinanceTabs/FinanceTabs'
import FinanceSettings from './FinanceSettings'
import { api, downloadApiFile, fileToBase64, openApiFile } from '../../services/api'

const fieldClass = 'h-10 w-full rounded-xl border border-[#d7e1e7] bg-white px-3 text-xs outline-none transition focus:border-[#4c8fc8] focus:ring-2 focus:ring-[#4c8fc8]/15'
const statusLabels = { issued:'รอชำระ', partial:'ชำระบางส่วน', paid:'ชำระแล้ว', cancelled:'ยกเลิก', pending:'รอตรวจ', approved:'อนุมัติแล้ว', rejected:'ไม่ผ่าน', draft:'ฉบับร่าง', submitted:'รออนุมัติ' }
const statusTone = { issued:'bg-[#fff7e4] text-[#8d6112]', partial:'bg-[#edf5fb] text-[#397caf]', paid:'bg-[#edf7f4] text-[#26715e]', approved:'bg-[#edf7f4] text-[#26715e]', pending:'bg-[#fff7e4] text-[#8d6112]', submitted:'bg-[#fff7e4] text-[#8d6112]', rejected:'bg-[#fff0ee] text-[#b74e44]', cancelled:'bg-[#f1f3f5] text-[#768591]', draft:'bg-[#edf5fb] text-[#397caf]' }

function Finance({ notify, user }) {
  const tenantPortal = Boolean(user?.tenant_id)
  const canManage = user?.permissions?.includes('finance.manage')
  const canApprove = user?.permissions?.includes('finance.approve')
  const canCancel = user?.permissions?.includes('finance.cancel')
  const [tab,setTab]=useState('invoices')
  const [data,setData]=useState({invoices:[],proofs:[],receipts:[],remittances:[],tenants:[],accounts:[],feeTypes:[],delinquency:{rows:[]}})
  const [loading,setLoading]=useState(true)
  const [modal,setModal]=useState(null)
  const [query,setQuery]=useState('')

  const load=async()=>{setLoading(true);try{
    const paths=[['invoices','/invoices'],['proofs','/payment-proofs'],['receipts','/receipts']]
    if(!tenantPortal) paths.push(['remittances','/remittances'],['accounts','/financial-accounts'],['delinquency','/finance/delinquency'])
    if(canManage) paths.push(['tenants','/tenants'],['feeTypes','/fee-types'])
    const result=await Promise.all(paths.map(async([key,path])=>[key,await api(path)]))
    setData(current=>({...current,...Object.fromEntries(result)}))
  }catch(error){notify(error.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[])

  const filtered=useMemo(()=>data.invoices.filter(x=>`${x.invoice_no}${x.tenant_code}${x.first_name}${x.last_name}${x.item_summary}`.toLowerCase().includes(query.toLowerCase())),[data.invoices,query])
  const outstanding=data.invoices.filter(x=>['issued','partial'].includes(x.status))
  const workflow=[
    ['ใบแจ้งหนี้',money(outstanding.reduce((s,x)=>s+x.balance,0)),ReceiptText,'ยอดคงเหลือ','บาท'],
    ['หลักฐาน',data.proofs.filter(x=>x.status==='pending').length,Paperclip,'รอตรวจสอบ','รายการ'],
    ['ใบเสร็จ',data.receipts.filter(x=>x.status==='issued').length,FileCheck2,'ออกแล้วทั้งหมด','ฉบับ'],
    ['นำส่งเงิน',data.remittances.filter(x=>x.status==='submitted').length,Landmark,'รอผู้บริหาร','รายการ'],
  ]

  const run=async(action,message)=>{try{await action();setModal(null);notify(message);await load()}catch(error){notify(error.message)}}
  const cancelDocument=(type,item)=>setModal({type:'cancel',documentType:type,item})

  return <div className="enter-up space-y-5">
    <section className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><div className="flex items-center gap-2 text-[10px] font-semibold text-[#397caf]"><CircleDollarSign size={13}/> ศูนย์งานการเงิน 4.5.4–4.7</div><h2 className="mt-1 text-[25px] font-semibold tracking-[-.02em] text-[#152c46]">จากตั้งหนี้ ถึงปิดยอดนำส่ง</h2><p className="mt-1 text-xs text-[#718493]">เอกสารทุกฉบับตรวจสอบย้อนหลังได้ และการยกเลิกต้องระบุเหตุผล</p></div>{canManage&&<div className="flex flex-wrap gap-2"><button onClick={()=>run(()=>api('/finance/assess-late-fees',{method:'POST',body:{asOf:new Date().toISOString().slice(0,10)}}),'ประเมินค่าปรับจาก Config แล้ว')} className="action-secondary"><RefreshCw size={15}/> ประเมินค่าปรับ</button><button onClick={()=>setModal({type:'payment'})} className="action-secondary"><Banknote size={15}/> รับชำระหน้าเคาน์เตอร์</button><button onClick={()=>setModal({type:'invoice'})} className="action-primary"><FilePlus2 size={15}/> ออกใบแจ้งหนี้</button></div>}</section>

    <section aria-label="ขั้นตอนปิดยอดรายวัน" className="grid overflow-hidden rounded-2xl border border-[#dce6eb] bg-white md:grid-cols-4">{workflow.map(([label,value,Icon,note,unit],index)=><button key={label} onClick={()=>setTab(['invoices','proofs','receipts','remittances'][index])} disabled={tenantPortal&&index===3} className="group relative flex items-center gap-3 border-b border-[#e6ecef] p-4 text-left last:border-0 disabled:cursor-default disabled:opacity-40 md:border-b-0 md:border-r"><span className="grid size-10 place-items-center rounded-xl bg-[#edf5fb] text-[#397caf]"><Icon size={18}/></span><span><b className="block text-xs text-[#2b455c]">{label}</b><span className="mt-1 block text-[10px] text-[#7d8e9b]">{note} · {value} {unit}</span></span>{index<3&&<span className="absolute -right-2 top-1/2 z-10 hidden size-4 -translate-y-1/2 rotate-45 border-r border-t border-[#dce6eb] bg-white md:block"/>}</button>)}</section>

    <section className="overflow-hidden rounded-2xl border border-[#dfe7eb] bg-white shadow-[0_2px_12px_rgba(22,45,68,.04)]"><FinanceTabs active={tab} onChange={setTab} tenantPortal={tenantPortal}/><div className="p-5">
      {loading?<Loading/>:<>
        {tab==='invoices'&&<Invoices rows={filtered} query={query} setQuery={setQuery} canManage={canManage} canCancel={canCancel} tenantPortal={tenantPortal} onProof={item=>setModal({type:'proof',item})} onPayment={item=>setModal({type:'payment',item})} onCancel={item=>cancelDocument('invoice',item)} onSend={item=>run(()=>api(`/invoices/${item.id}/send`,{method:'POST',body:{}}),'ส่งใบแจ้งหนี้ผ่านระบบ/email แล้ว')}/>}
        {tab==='proofs'&&<Proofs rows={data.proofs} canApprove={canApprove} onView={item=>openApiFile(`/payment-proofs/${item.id}/file`)} onReview={(item,decision)=>setModal({type:'review',item,decision})}/>}
        {tab==='receipts'&&<Receipts rows={data.receipts} canCancel={canCancel} onCancel={item=>cancelDocument('receipt',item)}/>}
        {tab==='remittances'&&!tenantPortal&&<Remittances rows={data.remittances} accounts={data.accounts} delinquency={data.delinquency?.rows||[]} canManage={canManage} canApprove={canApprove} canCancel={canCancel} onCreate={()=>setModal({type:'remittance'})} onBankImport={()=>setModal({type:'bank-import'})} onSubmit={item=>run(()=>api(`/remittances/${item.id}/submit`,{method:'POST',body:{}}),'ส่งรายการให้ผู้บริหารอนุมัติแล้ว')} onApprove={item=>setModal({type:'approve-remittance',item})} onCancel={item=>cancelDocument('remittance',item)}/>}
        {tab==='settings'&&!tenantPortal&&<FinanceSettings notify={notify} canManage={canManage}/>}
      </>}
    </div></section>
    {modal&&<FinanceDialog modal={modal} invoices={outstanding} tenants={data.tenants} feeTypes={data.feeTypes} close={()=>setModal(null)} submit={(payload)=>handleSubmit(modal,payload,run)}/>}
  </div>
}

async function handleSubmit(modal,payload,run){
  if(modal.type==='invoice')return run(()=>api('/invoices',{method:'POST',body:{tenantId:Number(payload.tenantId),dueDate:payload.dueDate,items:[{feeTypeId:Number(payload.feeTypeId),description:payload.description||undefined,quantity:1}]}}),'ออกใบแจ้งหนี้จากอัตรา Config แล้ว')
  if(modal.type==='payment')return run(()=>api('/payments',{method:'POST',body:{invoiceId:Number(payload.invoiceId),amount:Number(payload.amount),method:payload.method,referenceNo:payload.referenceNo||undefined}}),'รับชำระและออกใบเสร็จแล้ว')
  if(modal.type==='proof')return run(async()=>{const file=payload.file;if(!file)throw new Error('กรุณาเลือกหลักฐานการชำระ');if(file.size>3_000_000)throw new Error('ไฟล์หลักฐานต้องไม่เกิน 3 MB');const fileBase64=await fileToBase64(file);return api('/payment-proofs',{method:'POST',body:{invoiceId:Number(payload.invoiceId),amount:Number(payload.amount),referenceNo:payload.referenceNo||undefined,paidAt:new Date(payload.paidAt).toISOString(),filename:file.name,mimeType:file.type,fileBase64}})},'แนบหลักฐานแล้ว รอเจ้าหน้าที่ตรวจสอบ')
  if(modal.type==='review')return run(()=>api(`/payment-proofs/${modal.item.id}/review`,{method:'POST',body:{decision:modal.decision,note:payload.note}}),modal.decision==='approved'?'ตรวจหลักฐานและออกใบเสร็จแล้ว':'บันทึกผลไม่อนุมัติหลักฐานแล้ว')
  if(modal.type==='remittance')return run(()=>api('/remittances',{method:'POST',body:{date:payload.date,holdingStatementAmount:Number(payload.holdingStatementAmount),cashDepositReference:payload.cashDepositReference||undefined}}),'กระทบยอดบัญชีพักและสร้างรายการนำส่งแล้ว')
  if(modal.type==='bank-import')return run(async()=>{const file=payload.file;if(!file)throw new Error('กรุณาเลือกไฟล์ CSV');return api('/bank-imports',{method:'POST',body:{bankCode:payload.bankCode,filename:file.name,csv:await file.text()}})},'นำเข้าและกระทบยอดรายการธนาคารแล้ว')
  if(modal.type==='approve-remittance')return run(()=>api(`/remittances/${modal.item.id}/approve`,{method:'POST',body:{revenueTransferReference:payload.revenueTransferReference||undefined,depositTransferReference:payload.depositTransferReference||undefined,universityReceiptNo:payload.universityReceiptNo}}),'อนุมัติและออกเลขนำส่งเงินแล้ว')
  if(modal.type==='cancel')return run(()=>api(`/${modal.documentType==='invoice'?'invoices':modal.documentType==='receipt'?'receipts':'remittances'}/${modal.item.id}/cancel`,{method:'POST',body:{reason:payload.reason}}),'ยกเลิกรายการพร้อมบันทึกเหตุผลแล้ว')
}

function Invoices({rows,query,setQuery,canManage,canCancel,tenantPortal,onProof,onPayment,onCancel,onSend}){return <div><Header title="ทะเบียนใบแจ้งหนี้" detail="ออก ส่ง ตรวจสอบ และดาวน์โหลดเอกสารจากข้อมูลชุดเดียว"><label className="search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาเลขที่ ชื่อ หรือรายการ"/></label></Header><Table headers={['เลขที่ / ผู้เช่า','รายการ','กำหนดชำระ','ยอดคงเหลือ','สถานะ','ดำเนินการ']}>{rows.map(x=><tr key={x.id}><Cell><b>{x.invoice_no}</b><small>{x.tenant_code} · {x.first_name} {x.last_name}</small></Cell><Cell>{x.item_summary||'-'}</Cell><Cell>{date(x.due_date)}</Cell><Cell><b>{money(x.balance)}</b><small>จาก {money(x.total)} บาท</small></Cell><Cell><Status value={x.status}/></Cell><Cell><div className="row-actions"><button title="ดาวน์โหลดใบแจ้งหนี้" onClick={()=>downloadApiFile(`/invoices/${x.id}/document`,`${x.invoice_no}.pdf`)}><Download/></button>{['issued','partial'].includes(x.status)&&<>{tenantPortal&&<button title="แนบหลักฐาน" onClick={()=>onProof(x)}><Upload/></button>}{canManage&&<button title="รับชำระ" onClick={()=>onPayment(x)}><Banknote/></button>}{canManage&&<button title="ส่งผ่าน email" onClick={()=>onSend(x)}><Mail/></button>}</>}{canCancel&&x.status==='issued'&&<button title="ยกเลิก" className="danger" onClick={()=>onCancel(x)}><XCircle/></button>}</div></Cell></tr>)}</Table>{rows.length===0&&<Empty text="ยังไม่มีใบแจ้งหนี้ตามคำค้น"/>}</div>}

function Proofs({rows,canApprove,onView,onReview}){return <div><Header title="หลักฐานการชำระเงิน" detail="อนุมัติแล้วระบบจึงบันทึกรับเงินและออกใบเสร็จ"/><Table headers={['ใบแจ้งหนี้ / ผู้ชำระ','วันที่และอ้างอิง','จำนวนเงิน','ไฟล์','สถานะ','ตรวจสอบ']}>{rows.map(x=><tr key={x.id}><Cell><b>{x.invoice_no}</b><small>{x.tenant_code} · {x.first_name} {x.last_name}</small></Cell><Cell>{dateTime(x.paid_at)}<small>{x.reference_no||'ไม่ระบุเลขอ้างอิง'}</small></Cell><Cell><b>{money(x.amount)} บาท</b></Cell><Cell><button className="text-link" onClick={()=>onView(x)}><Paperclip size={13}/>{x.filename}</button></Cell><Cell><Status value={x.status}/>{x.review_note&&<small>{x.review_note}</small>}</Cell><Cell>{canApprove&&x.status==='pending'&&<div className="row-actions"><button className="approve" onClick={()=>onReview(x,'approved')} title="อนุมัติ"><Check/></button><button className="danger" onClick={()=>onReview(x,'rejected')} title="ไม่อนุมัติ"><X/></button></div>}</Cell></tr>)}</Table>{rows.length===0&&<Empty text="ยังไม่มีหลักฐานการชำระเงิน"/>}</div>}

function Receipts({rows,canCancel,onCancel}){return <div><Header title="ทะเบียนใบเสร็จรับเงิน" detail="ผู้เช่าดาวน์โหลดได้เฉพาะใบเสร็จของตนเอง"/><Table headers={['เลขที่ / ผู้ชำระ','ใบแจ้งหนี้','วันที่รับ','ช่องทาง','จำนวนเงิน','สถานะ / ดำเนินการ']}>{rows.map(x=><tr key={x.id}><Cell><b>{x.receipt_no}</b><small>{x.tenant_code} · {x.first_name} {x.last_name}</small></Cell><Cell>{x.invoice_no}</Cell><Cell>{dateTime(x.paid_at)}</Cell><Cell>{method(x.method)}<small>{x.reference_no}</small></Cell><Cell><b>{money(x.amount)} บาท</b></Cell><Cell><div className="flex items-center gap-2"><Status value={x.status}/><div className="row-actions"><button title="ดาวน์โหลดใบเสร็จ" onClick={()=>downloadApiFile(`/receipts/${x.id}/document`,`${x.receipt_no}.pdf`)}><Download/></button>{canCancel&&x.status==='issued'&&<button className="danger" title="ยกเลิกใบเสร็จ" onClick={()=>onCancel(x)}><XCircle/></button>}</div></div></Cell></tr>)}</Table>{rows.length===0&&<Empty text="ยังไม่มีใบเสร็จรับเงิน"/>}</div>}

function Remittances({rows,accounts,delinquency,canManage,canApprove,canCancel,onCreate,onBankImport,onSubmit,onApprove,onCancel}){return <div className="space-y-5"><Header title="การนำส่งเงินรายได้ประจำวัน" detail="กระทบบัญชีพัก แยกรายได้/เงินประกัน แล้วส่ง Maker–Checker"><div className="flex gap-2">{canManage&&<button onClick={onBankImport} className="action-secondary"><Upload size={14}/> นำเข้าไฟล์ธนาคาร</button>}{canManage&&<button onClick={onCreate} className="action-primary"><RefreshCw size={14}/> กระทบยอดวันนี้</button>}</div></Header><div className="grid gap-3 md:grid-cols-3">{accounts.map(x=><article key={x.purpose} className="rounded-xl border border-[#dfe7eb] bg-[#f8fafb] p-4"><p className="text-[10px] text-[#718594]">{x.purpose}</p><p className="mt-2 text-xs font-semibold">{x.bank} · {x.accountNoMasked}</p><p className="mt-1 text-[9px] text-[#84939e]">{x.name} · {x.branch}</p><span className={`mt-3 inline-block rounded-full px-2 py-1 text-[9px] ${x.configured?'bg-[#edf7f4] text-[#26715e]':'bg-[#fff0ee] text-[#b74e44]'}`}>{x.configured?'กำหนดแล้ว':'รอตั้งค่า Environment'}</span></article>)}</div>{delinquency.length>0&&<div className="rounded-xl border border-[#f1d7a2] bg-[#fff9ea] p-4"><b className="text-xs text-[#7b570d]">ติดตามผู้ค้างชำระ {delinquency.length} ราย</b><div className="mt-3 grid gap-2 md:grid-cols-2">{delinquency.slice(0,6).map(x=><div key={x.tenant_id} className="rounded-lg bg-white px-3 py-2 text-[10px]"><b>{x.tenant_code} · {x.tenant_name}</b><span className="ml-2">{money(x.outstanding_balance)} บาท</span><small>{x.threshold_reached?x.required_action:`ค้าง ${x.overdue_months} รอบ`}</small></div>)}</div></div>}<Table headers={['เลขนำส่ง / วันที่','รายได้มหาวิทยาลัย','เงินประกัน','เงินสด / โอน','สถานะ','ดำเนินการ']}>{rows.map(x=><tr key={x.id}><Cell><b>{x.remittance_no}</b><small>{date(x.remittance_date)} · กระทบต่าง {money(x.reconciliation_difference)}</small></Cell><Cell><b>{money(x.revenue_amount)} บาท</b><small>{x.revenue_transfer_reference}</small></Cell><Cell><b>{money(x.deposit_amount)} บาท</b><small>{x.deposit_transfer_reference}</small></Cell><Cell>{money(x.cash_amount)} / {money(x.transfer_amount)}<small>{x.cash_deposit_reference}</small></Cell><Cell><Status value={x.status}/>{x.university_receipt_no&&<small>ใบเสร็จ มสด. {x.university_receipt_no}</small>}</Cell><Cell><div className="row-actions">{canManage&&x.status==='draft'&&<button title="ส่งอนุมัติ" onClick={()=>onSubmit(x)}><Send/></button>}{canApprove&&x.status==='submitted'&&<button className="approve" title="อนุมัติ (ต้องไม่ใช่ผู้จัดทำ)" onClick={()=>onApprove(x)}><ShieldCheck/></button>}{canCancel&&x.status!=='cancelled'&&<button className="danger" title="ยกเลิก" onClick={()=>onCancel(x)}><XCircle/></button>}</div></Cell></tr>)}</Table>{rows.length===0&&<Empty text="ยังไม่มีรายการนำส่งเงิน"/>}</div>}

function FinanceDialog({modal,invoices,tenants,feeTypes,close,submit}){const [saving,setSaving]=useState(false);const title={invoice:'ออกใบแจ้งหนี้',payment:'รับชำระและออกใบเสร็จ',proof:'แนบหลักฐานการชำระ',review:modal.decision==='approved'?'อนุมัติหลักฐาน':'ไม่อนุมัติหลักฐาน',remittance:'กระทบยอดและนำส่งประจำวัน','bank-import':'นำเข้าไฟล์ธนาคาร','approve-remittance':'อนุมัติการนำส่งเงิน',cancel:'ยกเลิกรายการ'}[modal.type];const handle=async e=>{e.preventDefault();setSaving(true);try{await submit(Object.fromEntries(new FormData(e.currentTarget)))}finally{setSaving(false)}};return <div className="fixed inset-0 z-50 grid place-items-end bg-[#142a46]/45 sm:place-items-center sm:p-4" onMouseDown={e=>e.target===e.currentTarget&&close()}><form onSubmit={handle} className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-t-3xl bg-white shadow-2xl sm:rounded-3xl"><div className="flex items-center gap-3 border-b border-[#e5ebef] p-5"><span className="grid size-10 place-items-center rounded-xl bg-[#edf5fb] text-[#397caf]"><BadgeCheck size={18}/></span><div><h3 className="text-base font-semibold">{title}</h3><p className="text-[10px] text-[#7d8e9b]">ระบบบันทึกผู้ดำเนินการและวันเวลาใน History Log</p></div><button type="button" onClick={close} className="ml-auto grid size-9 place-items-center rounded-full bg-[#f2f5f7]"><X size={17}/></button></div><div className="grid gap-4 p-5">
  {modal.type==='invoice'&&<><Field label="ผู้เช่าที่มีสัญญาลงนาม"><select required name="tenantId" className={fieldClass}><option value="">เลือกผู้เช่า</option>{tenants.filter(x=>x.contract_document_status==='signed').map(x=><option key={x.id} value={x.id}>{x.tenant_code} · {x.first_name} {x.last_name}</option>)}</select></Field><Field label="รายการจาก Config"><select required name="feeTypeId" className={fieldClass}><option value="">เลือกค่าธรรมเนียม</option>{feeTypes.filter(x=>x.active&&x.default_amount>0).map(x=><option key={x.id} value={x.id}>{x.name} · {money(x.default_amount)} บาท</option>)}</select></Field><Field label="รายละเอียดเพิ่มเติม (ถ้ามี)"><input name="description" className={fieldClass}/></Field><Field label="กำหนดชำระ"><input required type="date" name="dueDate" className={fieldClass}/></Field></>}
  {modal.type==='payment'&&<><InvoiceSelect rows={invoices} selected={modal.item?.id}/><Field label="จำนวนเงิน"><input required min="0.01" step="0.01" type="number" name="amount" defaultValue={modal.item?.balance} className={fieldClass}/></Field><Field label="ช่องทางรับเงิน"><select name="method" className={fieldClass}><option value="cash">เงินสด</option><option value="transfer">เงินโอนเข้าบัญชีพัก</option><option value="online_account">บัญชีออนไลน์</option></select></Field><Field label="เลขอ้างอิง"><input name="referenceNo" className={fieldClass}/></Field></>}
  {modal.type==='proof'&&<><InvoiceSelect rows={invoices} selected={modal.item?.id}/><div className="grid grid-cols-2 gap-3"><Field label="จำนวนเงิน"><input required min="0.01" step="0.01" type="number" name="amount" defaultValue={modal.item?.balance} className={fieldClass}/></Field><Field label="วันเวลาที่ชำระ"><input required type="datetime-local" name="paidAt" className={fieldClass}/></Field></div><Field label="เลขอ้างอิง"><input name="referenceNo" className={fieldClass}/></Field><Field label="หลักฐาน JPG, PNG หรือ PDF ไม่เกิน 3 MB"><input required type="file" name="file" accept="image/jpeg,image/png,application/pdf" className={`${fieldClass} h-auto py-2`}/></Field></>}
  {modal.type==='review'&&<><Summary item={modal.item}/><Field label="ผลการตรวจสอบและหมายเหตุ"><textarea required minLength="5" name="note" rows="4" className={`${fieldClass} h-auto py-3`}/></Field></>}
  {modal.type==='remittance'&&<><p className="rounded-xl bg-[#f3f8fb] p-4 text-[11px] leading-5 text-[#526b7e]">กรอกยอดเครดิตในบัญชีพักของวันนั้น ระบบต้องเท่ากับใบเสร็จทุกฉบับจึงสร้างรายการได้ เงินสดต้องนำฝากและระบุเลขอ้างอิง</p><Field label="วันที่รับเงิน"><input required type="date" name="date" defaultValue={new Date().toISOString().slice(0,10)} className={fieldClass}/></Field><Field label="ยอดตาม Statement บัญชีพัก"><input required min="0" step="0.01" type="number" name="holdingStatementAmount" className={fieldClass}/></Field><Field label="เลขอ้างอิงนำฝากเงินสด (ถ้ามี)"><input name="cashDepositReference" className={fieldClass}/></Field></>}
  {modal.type==='bank-import'&&<><p className="rounded-xl bg-[#f3f8fb] p-4 text-[11px] leading-5 text-[#526b7e]">รองรับ CSV คอลัมน์ invoice_no, amount, reference_no, paid_at และป้องกันเลขอ้างอิงซ้ำ</p><Field label="ธนาคาร"><select name="bankCode" className={fieldClass}><option value="KASIKORN">กสิกรไทย</option></select></Field><Field label="ไฟล์ CSV"><input required type="file" name="file" accept=".csv,text/csv" className={`${fieldClass} h-auto py-2`}/></Field></>}
  {modal.type==='approve-remittance'&&<><Summary item={{invoice_no:modal.item.remittance_no,amount:modal.item.revenue_amount+modal.item.deposit_amount}}/><Field label="เลขอ้างอิงโอนรายได้เข้ามหาวิทยาลัย"><input name="revenueTransferReference" required={modal.item.revenue_amount>0} className={fieldClass}/></Field><Field label="เลขอ้างอิงโอนเงินประกัน"><input name="depositTransferReference" required={modal.item.deposit_amount>0} className={fieldClass}/></Field><Field label="เลขที่ใบเสร็จรับเงินเล่มมหาวิทยาลัย"><input required name="universityReceiptNo" className={fieldClass}/></Field></>}
  {modal.type==='cancel'&&<><Summary item={modal.item}/><Field label="เหตุผลการยกเลิก (บังคับ)"><textarea required minLength="5" name="reason" rows="4" className={`${fieldClass} h-auto py-3`}/></Field></>}
  </div><div className="flex gap-2 border-t border-[#e5ebef] p-4"><button type="button" onClick={close} className="flex-1 rounded-xl border border-[#d8e2e7] py-2.5 text-xs">ปิด</button><button disabled={saving} className={`flex flex-1 items-center justify-center gap-2 rounded-xl py-2.5 text-xs font-semibold ${modal.type==='cancel'||(modal.type==='review'&&modal.decision==='rejected')?'bg-[#b74e44] text-white':'bg-[#f5bf3c] text-[#173653]'}`}>{saving&&<LoaderCircle size={14} className="animate-spin"/>} ยืนยันรายการ</button></div></form></div>}

function Header({title,detail,children}){return <div className="mb-4 flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 text-[10px] text-[#7d8e9b]">{detail}</p></div>{children}</div>}
function Table({headers,children}){return <div className="overflow-x-auto rounded-xl border border-[#e0e8ec]"><table className="w-full min-w-[880px] text-left text-[11px]"><thead className="bg-[#f5f8f9] text-[#718392]"><tr>{headers.map(x=><th key={x} className="px-4 py-3 font-medium">{x}</th>)}</tr></thead><tbody className="divide-y divide-[#edf1f3]">{children}</tbody></table></div>}
function Cell({children}){return <td className="px-4 py-3 align-top text-[#40596e]">{children}</td>}
function Status({value}){return <span className={`inline-block rounded-full px-2.5 py-1 text-[9px] font-medium ${statusTone[value]||'bg-[#f1f3f5]'}`}>{statusLabels[value]||value}</span>}
function Field({label,children}){return <label><span className="mb-1.5 block text-[10px] font-medium text-[#617688]">{label}</span>{children}</label>}
function InvoiceSelect({rows,selected}){return <Field label="ใบแจ้งหนี้"><select required name="invoiceId" defaultValue={selected||''} className={fieldClass}><option value="">เลือกใบแจ้งหนี้</option>{rows.map(x=><option key={x.id} value={x.id}>{x.invoice_no} · {x.first_name} {x.last_name} · คงเหลือ {money(x.balance)}</option>)}</select></Field>}
function Summary({item}){return <div className="rounded-xl border border-[#dce6eb] bg-[#f6f9fa] p-4"><b className="text-xs">{item.invoice_no||item.receipt_no||item.remittance_no||item.filename}</b><p className="mt-1 text-[10px] text-[#718594]">{item.first_name} {item.last_name} · {money(item.amount||item.total||0)} บาท</p></div>}
function Empty({text}){return <div className="py-12 text-center text-xs text-[#82919c]">{text}</div>}
function Loading(){return <div className="grid min-h-48 place-items-center"><LoaderCircle className="animate-spin text-[#397caf]"/></div>}
function money(value){return Number(value||0).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2})}
function date(value){return value?new Date(value).toLocaleDateString('th-TH',{dateStyle:'medium'}):'-'}
function dateTime(value){return value?new Date(value).toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'}):'-'}
function method(value){return({cash:'เงินสด',transfer:'เงินโอน',bank_file:'ไฟล์ธนาคาร',online_account:'บัญชีออนไลน์'})[value]||value}
export default Finance
