import { useMemo, useState } from 'react'
import {
  ArrowDownToLine, Banknote, Building2, CalendarDays, CheckCircle2, ChevronRight,
  CircleDollarSign, Clock3, Download, FileBarChart, FilePlus2, FileSpreadsheet,
  Landmark, Plus, ReceiptText, Search, Settings2, UploadCloud, Users, WalletCards,
  XCircle,
} from 'lucide-react'
import FinanceTabs from '../../components/FinanceTabs/FinanceTabs'
import MoneyFlow from '../../components/MoneyFlow/MoneyFlow'
import InvoiceTable from '../../components/InvoiceTable/InvoiceTable'
import FinanceModal from '../../components/FinanceModal/FinanceModal'

const invoices = [
  { no:'INV-6907-0842', name:'ณัฐชา แสงทอง', personId:'65010234', personType:'นักศึกษา', type:'ค่าห้อง + น้ำ–ไฟ', due:'31 ก.ค. 2569', amount:4120, status:'overdue' },
  { no:'INV-6907-0841', name:'กวินท์ ศรีสุข', personId:'66010582', personType:'นักศึกษา', type:'ค่าห้องพัก', due:'05 ส.ค. 2569', amount:3850, status:'pending' },
  { no:'INV-6907-0840', name:'วิชาญ ศรีสุข', personId:'EMP0042', personType:'บุคลากร', type:'ค่าห้อง + ค่าไฟ', due:'05 ส.ค. 2569', amount:5220, status:'paid' },
  { no:'INV-6907-0839', name:'มาเรีย โรดริเกซ', personId:'EXT0098', personType:'บุคคลภายนอก', type:'ค่าเช่ารายวัน', due:'27 ก.ค. 2569', amount:1800, status:'paid' },
  { no:'INV-6907-0838', name:'ธนพล แก้วใส', personId:'65010881', personType:'นักศึกษา', type:'ค่าห้องพัก', due:'31 ก.ค. 2569', amount:3850, status:'cancelled' },
]

const reports = [
  ['สรุปใบแจ้งหนี้', 'รายวัน / รายเดือน', ReceiptText, 'invoice'],
  ['รายรับแยกประเภทรายการ', 'ค่าห้อง น้ำ ไฟ ประกัน ค่าปรับ', FileBarChart, 'revenue'],
  ['รับเงินตามผู้ออกใบเสร็จ', 'ตรวจสอบรายเจ้าหน้าที่', Users, 'cashier'],
  ['ใบนำส่งเงินประจำวัน', 'แยกตามประเภทเงินที่รับ', Landmark, 'remittance'],
  ['ลูกหนี้คงเหลือและอายุหนี้', 'ภาพรวม / รายตัวลูกหนี้', Clock3, 'debtor'],
  ['ผู้ทำสัญญา', 'ตามประเภทและช่วงสัญญา', FileSpreadsheet, 'contract'],
  ['ผู้มีเงินประกันห้องพัก', 'ยอดรับและสถานะการคืน', WalletCards, 'deposit'],
  ['ทะเบียนใบเสร็จรับเงิน', 'เรียงตามเลขที่ใบเสร็จ', Banknote, 'receipt'],
]

const rates = [
  { title:'อัตราค่าห้องพัก', icon:Building2, items:[['รายวัน','฿600 / วัน'],['รายเดือน','฿3,500 / เดือน'],['รายเทอม','฿8,500 / เทอม'],['รายปี','฿16,000 / ปี']] },
  { title:'ค่าสาธารณูปโภค', icon:CircleDollarSign, items:[['ค่าไฟฟ้า','฿7.00 / หน่วย'],['ค่าน้ำประปา','฿18.00 / หน่วย'],['ค่าน้ำขั้นต่ำ','฿100 / ห้อง']] },
  { title:'ค่าธรรมเนียมอื่น', icon:ReceiptText, items:[['เงินประกัน','฿3,000'],['ค่าปรับล่าช้า','฿50 / วัน'],['ค่าบัตรหอพัก','฿100']] },
]

function Metric({ label, value, note, icon:Icon, tone }) {
  return <div className="rounded-2xl border border-[#dfe7eb] bg-white p-4 shadow-[0_2px_10px_rgba(22,45,68,.035)]"><div className="flex items-start justify-between"><div><p className="text-[10px] text-[#728493]">{label}</p><p className="mt-1.5 font-['IBM_Plex_Sans'] text-xl font-semibold text-[#1e3851]">{value}</p></div><div className={`grid size-9 place-items-center rounded-xl ${tone}`}><Icon size={17}/></div></div><p className="mt-2 text-[10px] text-[#8997a2]">{note}</p></div>
}

function Finance({ notify }) {
  const [tab, setTab] = useState('overview')
  const [modal, setModal] = useState(null)
  const [selectedInvoice, setSelectedInvoice] = useState(null)
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('all')
  const filtered = useMemo(() => invoices.filter(item => (status === 'all' || item.status === status) && `${item.no}${item.name}${item.personId}`.toLowerCase().includes(query.toLowerCase())), [query, status])

  const openModal = (mode, invoice = null) => { setSelectedInvoice(invoice); setModal(mode) }
  const confirm = data => { setModal(null); notify(modal === 'invoice' ? 'ออกใบแจ้งหนี้เรียบร้อยแล้ว' : modal === 'payment' ? 'รับชำระและออกใบเสร็จเรียบร้อยแล้ว' : `ยกเลิกเอกสารแล้ว · ${data.reason}`) }

  return <div className="enter-up space-y-5">
    <section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="flex items-center gap-2 text-[10px] font-medium text-[#41749e]"><CircleDollarSign size={13}/> ศูนย์งานการเงินหอพัก</div><h2 className="mt-1 text-[25px] font-semibold tracking-[-.02em] text-[#152c46]">รับเงินครบ ตรวจสอบได้ นำส่งตรงรอบ</h2><p className="mt-1 text-xs text-[#748594]">จัดการตั้งหนี้ รับชำระ ใบเสร็จ ธนาคาร และรายงานในพื้นที่เดียว</p></div><div className="flex gap-2"><button onClick={() => openModal('payment')} className="flex items-center gap-2 rounded-xl border border-[#cfdde4] bg-white px-4 py-2.5 text-xs font-semibold text-[#2c526c]"><Banknote size={16}/> รับชำระเงิน</button><button onClick={() => openModal('invoice')} className="flex items-center gap-2 rounded-xl bg-[#f5bf3c] px-4 py-2.5 text-xs font-semibold text-[#173653] shadow-[0_3px_0_#c28d15]"><FilePlus2 size={16}/> ตั้งหนี้ใหม่</button></div></section>

    <section className="overflow-hidden rounded-2xl border border-[#dfe7eb] bg-white shadow-[0_2px_12px_rgba(22,45,68,.04)]"><FinanceTabs active={tab} onChange={setTab}/>
      <div className="p-5">
        {tab === 'overview' && <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="รายรับวันนี้" value="฿354,850" note="96 รายการ · เพิ่ม 8.2%" icon={CircleDollarSign} tone="bg-[#edf7f4] text-[#2f7d68]"/><Metric label="ยอดค้างชำระ" value="฿128,450" note="42 รายการ · เกินกำหนด 12" icon={Clock3} tone="bg-[#fff0ee] text-[#bd493f]"/><Metric label="รอตรวจหลักฐาน" value="7 รายการ" note="มูลค่า ฿24,780" icon={ReceiptText} tone="bg-[#fff7e4] text-[#ad7210]"/><Metric label="พร้อมนำส่ง" value="฿354,850" note="รอบนำส่ง 16:30 น." icon={Landmark} tone="bg-[#edf5fb] text-[#397caf]"/></div><MoneyFlow/>
          <div className="grid gap-4 lg:grid-cols-[1.5fr_.8fr]"><div className="rounded-2xl border border-[#e0e8ec]"><div className="flex items-center justify-between border-b border-[#e7edf0] p-4"><div><h3 className="text-sm font-semibold">รายการที่ต้องติดตาม</h3><p className="mt-0.5 text-[10px] text-[#84929d]">เรียงตามความเร่งด่วน</p></div><button onClick={() => setTab('invoices')} className="text-[10px] font-medium text-[#397caf]">ดูใบแจ้งหนี้ทั้งหมด</button></div><InvoiceTable invoices={invoices.slice(0,3)} onCancel={item=>openModal('cancel',item)} onReceive={item=>openModal('payment',item)}/></div>
            <div className="rounded-2xl border border-[#e0e8ec] p-4"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">รายรับ 7 วัน</h3><span className="text-[10px] text-[#8695a2]">หน่วย: พันบาท</span></div><div className="mt-5 flex h-36 items-end justify-between gap-2">{[42,68,55,82,64,92,78].map((height,index)=><div key={index} className="flex flex-1 flex-col items-center gap-2"><div className={`w-full rounded-t-md ${index===5?'bg-[#f5bf3c]':'bg-[#c8dce9]'}`} style={{height:`${height}%`}}/><span className="text-[9px] text-[#8998a3]">{['จ','อ','พ','พฤ','ศ','ส','อา'][index]}</span></div>)}</div><div className="mt-3 flex items-center justify-between border-t border-[#edf1f3] pt-3"><span className="text-[10px] text-[#7b8c99]">เฉลี่ยต่อวัน</span><span className="font-['IBM_Plex_Sans'] text-sm font-semibold">฿286,420</span></div></div></div></div>}

        {tab === 'invoices' && <div><div className="mb-4 flex flex-col gap-3 md:flex-row md:items-center"><div><h3 className="text-sm font-semibold">ใบแจ้งหนี้ทั้งหมด</h3><p className="mt-0.5 text-[10px] text-[#84929d]">ตั้งหนี้รายบุคคลและติดตามสถานะการชำระ</p></div><div className="md:ml-auto flex gap-2"><label className="flex h-9 w-full items-center gap-2 rounded-xl border border-[#d8e2e7] bg-[#f9fbfc] px-3 md:w-56"><Search size={14} className="text-[#80909c]"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full bg-transparent text-[11px] outline-none" placeholder="ค้นหาเลขที่หรือชื่อ"/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-[#d8e2e7] bg-white px-3 text-[11px]"><option value="all">ทุกสถานะ</option><option value="pending">รอชำระ</option><option value="overdue">เกินกำหนด</option><option value="paid">ชำระแล้ว</option><option value="cancelled">ยกเลิก</option></select></div></div><div className="overflow-hidden rounded-2xl border border-[#e0e8ec]"><InvoiceTable invoices={filtered} onCancel={item=>openModal('cancel',item)} onReceive={item=>openModal('payment',item)}/></div></div>}

        {tab === 'payments' && <div className="grid gap-4 lg:grid-cols-[.85fr_1.4fr]"><section className="rounded-2xl border border-[#dce6eb] bg-[#f8fafb] p-5"><div className="grid size-11 place-items-center rounded-xl bg-[#edf7f4] text-[#2f7d68]"><Banknote size={21}/></div><h3 className="mt-4 text-base font-semibold">รับชำระหน้าเคาน์เตอร์</h3><p className="mt-1 text-xs text-[#748694]">ค้นหาใบแจ้งหนี้ ตรวจยอด และออกใบเสร็จในขั้นตอนเดียว</p><button onClick={()=>openModal('payment')} className="mt-5 w-full rounded-xl bg-[#173653] py-3 text-xs font-semibold text-white">เริ่มรับชำระเงิน</button><div className="mt-5 space-y-2 border-t border-[#e1e8ec] pt-4">{[['เงินสด','฿48,500'],['เงินโอน','฿126,350'],['ธนาคาร','฿180,000']].map(item=><div key={item[0]} className="flex justify-between text-xs"><span className="text-[#6f8291]">{item[0]}</span><span className="font-['IBM_Plex_Sans'] font-semibold">{item[1]}</span></div>)}</div></section><section className="overflow-hidden rounded-2xl border border-[#dce6eb]"><div className="flex items-center justify-between border-b border-[#e5ebef] p-4"><div><h3 className="text-sm font-semibold">ใบเสร็จล่าสุด</h3><p className="text-[10px] text-[#83929e]">ออกโดยคุณสุภาวดี พรหมมา</p></div><button className="text-[10px] text-[#397caf]">ดูทะเบียนใบเสร็จ</button></div>{[['RC-690727-0142','ณัฐชา แสงทอง','฿4,120','15:32'],['RC-690727-0141','วิชาญ ศรีสุข','฿5,220','14:48'],['RC-690727-0140','มาเรีย โรดริเกซ','฿1,800','13:05'],['RC-690727-0139','กวินท์ ศรีสุข','฿3,850','11:42']].map(row=><div key={row[0]} className="flex items-center gap-3 border-b border-[#edf1f3] px-4 py-3 last:border-0"><div className="grid size-8 place-items-center rounded-lg bg-[#edf7f4] text-[#2f7d68]"><CheckCircle2 size={14}/></div><div className="flex-1"><p className="font-['IBM_Plex_Sans'] text-xs font-semibold">{row[0]}</p><p className="text-[10px] text-[#82919c]">{row[1]} · {row[3]} น.</p></div><p className="font-['IBM_Plex_Sans'] text-xs font-semibold">{row[2]}</p><button onClick={()=>openModal('cancel',{no:row[0],name:row[1],amount:Number(row[2].replace(/\D/g,''))})} className="grid size-8 place-items-center rounded-lg text-[#9b7376] hover:bg-[#fff0ee]" title="ยกเลิกใบเสร็จ"><XCircle size={14}/></button></div>)}</section></div>}

        {tab === 'bank' && <div className="grid gap-4 lg:grid-cols-[1fr_1fr]"><section className="rounded-2xl border-2 border-dashed border-[#cbdbe4] bg-[#f7fafb] p-7 text-center"><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-[#eaf3f8] text-[#397caf]"><UploadCloud size={22}/></div><h3 className="mt-4 text-sm font-semibold">นำเข้าไฟล์ชำระเงินจากธนาคาร</h3><p className="mx-auto mt-1 max-w-sm text-[10px] leading-5 text-[#7c8d9a]">รองรับ CSV ธนาคารกรุงไทย: invoice_no, amount, reference_no, paid_at</p><label className="mt-4 inline-flex cursor-pointer items-center gap-2 rounded-xl bg-[#173653] px-4 py-2.5 text-xs font-semibold text-white"><ArrowDownToLine size={15}/> เลือกไฟล์<input type="file" accept=".csv" className="hidden" onChange={()=>notify('เลือกไฟล์แล้ว พร้อมตรวจสอบก่อนนำเข้า')}/></label></section><section className="space-y-4"><div className="rounded-2xl border border-[#dce6eb] p-5"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-[#e8f2fa] text-[#397caf]"><Landmark size={19}/></div><div><p className="text-[10px] text-[#778a98]">บัญชีรับชำระออนไลน์</p><p className="font-['IBM_Plex_Sans'] text-sm font-semibold">กรุงไทย · 123-4-56789-0</p></div><span className="ml-auto rounded-full bg-[#edf7f4] px-2.5 py-1 text-[10px] font-medium text-[#2f7d68]">เชื่อมต่อแล้ว</span></div></div><div className="rounded-2xl border border-[#dce6eb]"><div className="border-b border-[#e7edf0] p-4"><h3 className="text-sm font-semibold">ประวัตินำเข้าล่าสุด</h3></div>{[['KTB_20260727.csv','128 รายการ','สำเร็จ 126 · ผิดพลาด 2'],['KTB_20260726.csv','94 รายการ','สำเร็จทั้งหมด']].map(row=><div key={row[0]} className="flex items-center gap-3 border-b border-[#edf1f3] p-4 last:border-0"><FileSpreadsheet size={17} className="text-[#56809f]"/><div className="flex-1"><p className="font-['IBM_Plex_Sans'] text-xs font-semibold">{row[0]}</p><p className="text-[10px] text-[#81909c]">{row[1]}</p></div><span className="text-[10px] text-[#5e7485]">{row[2]}</span><ChevronRight size={14}/></div>)}</div></section></div>}

        {tab === 'rates' && <div><div className="mb-4 flex items-end justify-between"><div><h3 className="text-sm font-semibold">อัตราและค่าธรรมเนียม</h3><p className="mt-0.5 text-[10px] text-[#82919d]">อัตราปัจจุบันมีผลตั้งแต่ 1 มิถุนายน 2569</p></div><button onClick={()=>notify('เปิดแบบฟอร์มเพิ่มอัตราใหม่')} className="flex items-center gap-1.5 rounded-xl border border-[#d5e0e6] px-3 py-2 text-[10px] font-medium"><Plus size={14}/> เพิ่มอัตรา</button></div><div className="grid gap-4 lg:grid-cols-3">{rates.map(group=><section key={group.title} className="rounded-2xl border border-[#dce6eb]"><div className="flex items-center gap-3 border-b border-[#e7edf0] p-4"><div className="grid size-9 place-items-center rounded-xl bg-[#edf5fb] text-[#397caf]"><group.icon size={17}/></div><h3 className="text-sm font-semibold">{group.title}</h3><button className="ml-auto text-[#7e8e9a]"><Settings2 size={15}/></button></div><div className="divide-y divide-[#edf1f3]">{group.items.map(item=><div key={item[0]} className="flex items-center justify-between px-4 py-3.5"><span className="text-xs text-[#637787]">{item[0]}</span><span className="font-['IBM_Plex_Sans'] text-xs font-semibold text-[#243e56]">{item[1]}</span></div>)}</div></section>)}</div><div className="mt-4 flex items-start gap-3 rounded-xl border border-[#efdda9] bg-[#fff9ea] p-4"><CalendarDays size={17} className="mt-0.5 text-[#a97412]"/><div><p className="text-xs font-medium text-[#73591f]">การเปลี่ยนอัตราจะไม่กระทบเอกสารย้อนหลัง</p><p className="mt-1 text-[10px] text-[#8d763e]">กำหนดวันเริ่ม–สิ้นสุดสำหรับอัตราใหม่ ระบบจะเลือกอัตราตามวันที่เกิดรายการ</p></div></div></div>}

        {tab === 'reports' && <div><div className="mb-4 flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><h3 className="text-sm font-semibold">ศูนย์รายงานการเงิน</h3><p className="mt-0.5 text-[10px] text-[#82919d]">ดูตัวอย่างก่อนพิมพ์หรือส่งออก HTML, PDF และ Excel</p></div><div className="flex gap-2"><input type="date" defaultValue="2026-07-27" className="h-9 rounded-xl border border-[#d8e2e7] px-3 text-[11px]"/><button className="flex items-center gap-1.5 rounded-xl border border-[#d8e2e7] px-3 text-[10px]"><Download size={14}/> ส่งออกทั้งหมด</button></div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{reports.map(([title,detail,Icon,id])=><button key={id} onClick={()=>notify(`เปิดรายงาน ${title}`)} className="group rounded-2xl border border-[#dce6eb] p-4 text-left transition hover:-translate-y-0.5 hover:border-[#abc4d3] hover:shadow-md"><div className="flex items-start justify-between"><div className="grid size-9 place-items-center rounded-xl bg-[#eef4f8] text-[#4d7897]"><Icon size={17}/></div><ChevronRight size={15} className="text-[#a1adb6] group-hover:text-[#397caf]"/></div><h4 className="mt-4 text-xs font-semibold text-[#284159]">{title}</h4><p className="mt-1 text-[10px] leading-4 text-[#81909c]">{detail}</p><div className="mt-4 flex gap-1"><span className="rounded bg-[#f1f4f6] px-1.5 py-0.5 text-[8px] text-[#6d7f8c]">PDF</span><span className="rounded bg-[#f1f4f6] px-1.5 py-0.5 text-[8px] text-[#6d7f8c]">Excel</span><span className="rounded bg-[#f1f4f6] px-1.5 py-0.5 text-[8px] text-[#6d7f8c]">HTML</span></div></button>)}</div></div>}
      </div>
    </section>
    <FinanceModal mode={modal} invoice={selectedInvoice} onClose={()=>setModal(null)} onConfirm={confirm}/>
  </div>
}

export default Finance
