import { useMemo, useState } from 'react'
import { AlertTriangle, ArrowDown, ArrowUp, Boxes, Download, Plus, Search, Sparkles, Wrench } from 'lucide-react'

const items=[
 {sku:'LIN-001',name:'ผ้าปูที่นอน 3.5 ฟุต',category:'อุปกรณ์หอพัก',unit:'ผืน',qty:126,min:40,location:'คลัง A-01'},
 {sku:'LIN-002',name:'ปลอกหมอนสีขาว',category:'อุปกรณ์หอพัก',unit:'ใบ',qty:38,min:50,location:'คลัง A-02'},
 {sku:'LIN-003',name:'ผ้าห่ม',category:'อุปกรณ์หอพัก',unit:'ผืน',qty:82,min:30,location:'คลัง A-03'},
 {sku:'MNT-014',name:'หลอดไฟ LED 18W',category:'อุปกรณ์ช่าง',unit:'หลอด',qty:24,min:20,location:'คลัง B-04'},
 {sku:'MNT-022',name:'ก๊อกน้ำสแตนเลส',category:'อุปกรณ์ช่าง',unit:'ชิ้น',qty:8,min:10,location:'คลัง B-07'},
 {sku:'CLN-006',name:'น้ำยาทำความสะอาดพื้น',category:'อุปกรณ์ทำความสะอาด',unit:'แกลลอน',qty:18,min:12,location:'คลัง C-03'},
]
const icons={'อุปกรณ์หอพัก':Boxes,'อุปกรณ์ช่าง':Wrench,'อุปกรณ์ทำความสะอาด':Sparkles}
function Inventory({notify}){const[category,setCategory]=useState('ทั้งหมด');const[query,setQuery]=useState('');const rows=useMemo(()=>items.filter(x=>(category==='ทั้งหมด'||x.category===category)&&`${x.sku}${x.name}`.toLowerCase().includes(query.toLowerCase())),[category,query]);return <div className="enter-up space-y-5"><section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="flex items-center gap-2 text-[10px] font-medium text-[#41749e]"><Boxes size={13}/> คลังอุปกรณ์หอพัก</div><h2 className="mt-1 text-[25px] font-semibold text-[#152c46]">รู้ยอดคงเหลือก่อนมีคนเบิก</h2><p className="mt-1 text-xs text-[#748594]">แยกอุปกรณ์หอพัก ช่าง และทำความสะอาด พร้อมจุดสั่งซื้อ</p></div><div className="flex gap-2"><button className="grid size-10 place-items-center rounded-xl border border-[#d5e0e6] bg-white"><Download size={15}/></button><button onClick={()=>notify('เปิดแบบฟอร์มเพิ่มอุปกรณ์')} className="flex items-center gap-2 rounded-xl bg-[#f5bf3c] px-4 py-2.5 text-xs font-semibold text-[#173653]"><Plus size={16}/> เพิ่มอุปกรณ์</button></div></section>
 <section className="grid gap-3 sm:grid-cols-3">{[['มูลค่าสต็อก','฿284,650','542 รายการ'],['ใกล้จุดสั่งซื้อ','7 รายการ','ควรตรวจสอบสัปดาห์นี้'],['เบิกจ่ายเดือนนี้','186 รายการ','42 ใบเบิก']].map((x,i)=><div key={x[0]} className="rounded-2xl border border-[#dfe7eb] bg-white p-4"><p className="text-[10px] text-[#748694]">{x[0]}</p><p className="mt-2 text-xl font-semibold">{x[1]}</p><p className={`mt-1 text-[10px] ${i===1?'text-[#bd493f]':'text-[#8795a1]'}`}>{x[2]}</p></div>)}</section>
 <section className="overflow-hidden rounded-2xl border border-[#dfe7eb] bg-white"><div className="flex flex-col gap-3 border-b border-[#e4eaee] p-4 md:flex-row md:items-center"><div className="flex flex-wrap gap-1 rounded-xl bg-[#f2f5f7] p-1">{['ทั้งหมด','อุปกรณ์หอพัก','อุปกรณ์ช่าง','อุปกรณ์ทำความสะอาด'].map(x=><button key={x} onClick={()=>setCategory(x)} className={`rounded-lg px-3 py-1.5 text-[10px] ${category===x?'bg-white font-medium shadow-sm':'text-[#748594]'}`}>{x}</button>)}</div><label className="flex h-9 items-center gap-2 rounded-xl border border-[#d8e2e7] px-3 md:ml-auto"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-44 text-[11px] outline-none" placeholder="ค้นหา SKU หรือชื่อ"/></label></div>
 <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-[#f8fafb] text-[10px] text-[#718392]"><tr><th className="px-5 py-3">อุปกรณ์</th><th className="px-4 py-3">ประเภท</th><th className="px-4 py-3">ตำแหน่ง</th><th className="px-4 py-3 text-right">คงเหลือ</th><th className="px-4 py-3">สถานะ</th><th className="px-5 py-3 text-right">เคลื่อนไหว</th></tr></thead><tbody className="divide-y divide-[#edf1f3]">{rows.map(row=>{const I=icons[row.category],low=row.qty<=row.min;return <tr key={row.sku} className="text-xs hover:bg-[#fafcfd]"><td className="px-5 py-3.5"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-[#eef4f7] text-[#527994]"><I size={16}/></div><div><p className="font-medium text-[#294259]">{row.name}</p><p className="font-['IBM_Plex_Sans'] text-[10px] text-[#84929d]">{row.sku}</p></div></div></td><td className="px-4 py-3.5 text-[#617687]">{row.category}</td><td className="px-4 py-3.5 text-[#617687]">{row.location}</td><td className="px-4 py-3.5 text-right"><span className="font-['IBM_Plex_Sans'] font-semibold">{row.qty}</span> <span className="text-[10px] text-[#84929d]">{row.unit}</span></td><td className="px-4 py-3.5"><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] ${low?'bg-[#fff0ee] text-[#bd493f]':'bg-[#edf7f4] text-[#2f7d68]'}`}>{low&&<AlertTriangle size={11}/>} {low?'ต่ำกว่าจุดสั่งซื้อ':'ปกติ'}</span></td><td className="px-5 py-3.5"><div className="flex justify-end gap-1"><button onClick={()=>notify(`รับเข้า ${row.name}`)} className="grid size-8 place-items-center rounded-lg bg-[#edf7f4] text-[#2f7d68]"><ArrowDown size={14}/></button><button onClick={()=>notify(`เบิกออก ${row.name}`)} className="grid size-8 place-items-center rounded-lg bg-[#fff7e4] text-[#ad7210]"><ArrowUp size={14}/></button></div></td></tr>})}</tbody></table></div></section></div>}
export default Inventory
