import { useEffect,useMemo,useState } from 'react'
import { AlertTriangle,ArrowDown,ArrowUp,Boxes,LoaderCircle,Plus,Search,Sparkles,Wrench,X } from 'lucide-react'
import { api } from '../../services/api'

const fieldClass='h-10 w-full rounded-xl border border-[#d8e2e7] bg-white px-3 text-xs outline-none focus:border-[#4c8fc8] focus:ring-2 focus:ring-[#4c8fc8]/15'
const categories={dormitory:'อุปกรณ์หอพัก',maintenance:'อุปกรณ์ช่าง',cleaning:'อุปกรณ์ทำความสะอาด',other:'อื่น ๆ'}
const icons={dormitory:Boxes,maintenance:Wrench,cleaning:Sparkles,other:Boxes}

function Inventory({notify,user}){
  const[items,setItems]=useState([]),[category,setCategory]=useState('all'),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[modal,setModal]=useState(null)
  const canManage=user?.permissions?.includes('inventory.manage')
  const load=async()=>{setLoading(true);try{setItems(await api('/inventory'))}catch(error){notify(error.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  const rows=useMemo(()=>items.filter(x=>(category==='all'||x.category===category)&&`${x.sku}${x.name}`.toLowerCase().includes(query.toLowerCase())),[items,category,query])
  const save=async event=>{event.preventDefault();setSaving(true);const form=Object.fromEntries(new FormData(event.currentTarget));try{if(modal.type==='create')await api('/inventory',{method:'POST',body:{sku:form.sku.trim().toUpperCase(),name:form.name,category:form.category,unit:form.unit,quantity:Number(form.quantity),reorderLevel:Number(form.reorderLevel)}});else await api(`/inventory/${modal.item.id}/movements`,{method:'POST',body:{type:modal.movement,quantity:Number(form.quantity),reference:form.reference||undefined}});notify(modal.type==='create'?'เพิ่มอุปกรณ์เข้าคลังแล้ว':'บันทึกการเคลื่อนไหวสต็อกแล้ว');setModal(null);await load()}catch(error){notify(error.message)}finally{setSaving(false)}}
  const total=items.reduce((sum,item)=>sum+item.quantity,0),low=items.filter(item=>item.quantity<=item.reorder_level).length
  return <div className="enter-up space-y-5"><section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="flex items-center gap-2 text-[10px] font-medium text-[#41749e]"><Boxes size={13}/> คลังอุปกรณ์หอพัก</div><h2 className="mt-1 text-[25px] font-semibold text-[#152c46]">สต็อกจริง เชื่อมการเบิกงานซ่อม</h2><p className="mt-1 text-xs text-[#748594]">แยกอุปกรณ์หอพัก ช่าง และทำความสะอาด ทุกการเบิกมี movement และ audit trail</p></div>{canManage&&<button onClick={()=>setModal({type:'create'})} className="flex items-center gap-2 rounded-xl bg-[#f5bf3c] px-4 py-2.5 text-xs font-semibold text-[#173653]"><Plus size={16}/> เพิ่มอุปกรณ์</button>}</section>
    <section className="grid gap-3 sm:grid-cols-3">{[['ยอดคงเหลือรวม',`${total.toLocaleString('th-TH')} หน่วย`,`${items.length} SKU`],['ใกล้จุดสั่งซื้อ',`${low} รายการ`,'ควรตรวจสอบและสั่งซื้อ'],['ประเภทคลัง',`${new Set(items.map(x=>x.category)).size} ประเภท`,'แยกตามการใช้งาน']].map((x,index)=><div key={x[0]} className="rounded-2xl border border-[#dfe7eb] bg-white p-4"><p className="text-[10px] text-[#748694]">{x[0]}</p><p className="mt-2 text-xl font-semibold">{x[1]}</p><p className={`mt-1 text-[10px] ${index===1&&low?'text-[#bd493f]':'text-[#8795a1]'}`}>{x[2]}</p></div>)}</section>
    <section className="overflow-hidden rounded-2xl border border-[#dfe7eb] bg-white"><div className="flex flex-col gap-3 border-b border-[#e4eaee] p-4 md:flex-row md:items-center"><div className="flex flex-wrap gap-1 rounded-xl bg-[#f2f5f7] p-1">{[['all','ทั้งหมด'],...Object.entries(categories)].map(([value,label])=><button key={value} onClick={()=>setCategory(value)} className={`rounded-lg px-3 py-1.5 text-[10px] ${category===value?'bg-white font-medium shadow-sm':'text-[#748594]'}`}>{label}</button>)}</div><label className="flex h-9 items-center gap-2 rounded-xl border border-[#d8e2e7] px-3 md:ml-auto"><Search size={14}/><input value={query} onChange={event=>setQuery(event.target.value)} className="w-44 text-[11px] outline-none" placeholder="ค้นหา SKU หรือชื่อ"/></label></div>
      {loading?<div className="grid min-h-72 place-items-center"><LoaderCircle className="animate-spin text-[#397caf]"/></div>:<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-[#f8fafb] text-[10px] text-[#718392]"><tr>{['อุปกรณ์','ประเภท','คงเหลือ','จุดสั่งซื้อ','สถานะ','เคลื่อนไหว'].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-[#edf1f3]">{rows.map(row=>{const Icon=icons[row.category],isLow=row.quantity<=row.reorder_level;return <tr key={row.id} className="text-xs"><td className="px-5 py-3.5"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#eef4f7] text-[#527994]"><Icon size={16}/></span><span><b className="block text-[#294259]">{row.name}</b><small>{row.sku}</small></span></div></td><td className="px-5 py-3.5">{categories[row.category]}</td><td className="px-5 py-3.5 font-semibold">{row.quantity} {row.unit}</td><td className="px-5 py-3.5">{row.reorder_level} {row.unit}</td><td className="px-5 py-3.5"><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] ${isLow?'bg-[#fff0ee] text-[#bd493f]':'bg-[#edf7f4] text-[#2f7d68]'}`}>{isLow&&<AlertTriangle size={11}/>} {isLow?'ถึงจุดสั่งซื้อ':'ปกติ'}</span></td><td className="px-5 py-3.5">{canManage&&<div className="flex gap-1"><button title="รับเข้า" onClick={()=>setModal({type:'movement',movement:'in',item:row})} className="grid size-8 place-items-center rounded-lg bg-[#edf7f4] text-[#2f7d68]"><ArrowDown size={14}/></button><button title="เบิกออก" onClick={()=>setModal({type:'movement',movement:'out',item:row})} className="grid size-8 place-items-center rounded-lg bg-[#fff7e4] text-[#ad7210]"><ArrowUp size={14}/></button></div>}</td></tr>})}</tbody></table>{rows.length===0&&<p className="py-12 text-center text-xs text-[#82919c]">ไม่พบอุปกรณ์</p>}</div>}</section>
    {modal&&<InventoryDialog modal={modal} saving={saving} close={()=>setModal(null)} save={save}/>} </div>
}

function InventoryDialog({modal,saving,close,save}){return <div className="fixed inset-0 z-50 grid place-items-end bg-[#142a46]/40 sm:place-items-center sm:p-4" onMouseDown={e=>e.target===e.currentTarget&&close()}><form onSubmit={save} className="w-full max-w-lg rounded-t-3xl bg-white p-6 shadow-2xl sm:rounded-3xl"><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold text-[#397caf]">Inventory ledger</p><h3 className="mt-1 text-xl font-semibold">{modal.type==='create'?'เพิ่มอุปกรณ์ใหม่':`${modal.movement==='in'?'รับเข้า':'เบิกออก'} · ${modal.item.name}`}</h3></div><button type="button" onClick={close} className="grid size-9 place-items-center rounded-full bg-[#f1f4f6]"><X size={17}/></button></div><div className="mt-5 grid gap-4">{modal.type==='create'?<><div className="grid grid-cols-2 gap-3"><Field label="SKU"><input required name="sku" className={fieldClass}/></Field><Field label="หน่วยนับ"><input required name="unit" className={fieldClass}/></Field></div><Field label="ชื่ออุปกรณ์"><input required name="name" className={fieldClass}/></Field><Field label="ประเภทคลัง"><select name="category" className={fieldClass}>{Object.entries(categories).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="ยอดเริ่มต้น"><input required min="0" step="0.01" type="number" name="quantity" defaultValue="0" className={fieldClass}/></Field><Field label="จุดสั่งซื้อ"><input required min="0" step="0.01" type="number" name="reorderLevel" defaultValue="0" className={fieldClass}/></Field></div></>:<><Field label="จำนวน"><input required min="0.01" step="0.01" type="number" name="quantity" className={fieldClass}/></Field><Field label="เลขอ้างอิง / เหตุผล"><input required name="reference" className={fieldClass}/></Field></>}</div><button disabled={saving} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#f5bf3c] py-3 text-xs font-semibold text-[#173653]">{saving&&<LoaderCircle size={14} className="animate-spin"/>} บันทึกรายการ</button></form></div>}
function Field({label,children}){return <label><span className="mb-1.5 block text-[10px] font-medium text-[#657a8b]">{label}</span>{children}</label>}
export default Inventory
