import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, Clock3, KeyRound, LoaderCircle, LockKeyhole, Pencil, Plus, Search, ServerCog, ShieldCheck, Trash2, UserCog, Users, X } from 'lucide-react'
import { api } from '../../services/api'

const fieldClass = 'h-10 w-full rounded-xl border border-[#d7e1e7] bg-white px-3 text-xs outline-none transition focus:border-[#4c8fc8] focus:ring-2 focus:ring-[#4c8fc8]/15'
const tabs = [['users', 'ผู้ใช้งาน'], ['roles', 'กลุ่มและสิทธิ์'], ['registration', 'ทะเบียนเข้าใช้'], ['ldap', 'LDAP / AD'], ['logs', 'History Log']]

function Administration({ notify, user, initialTab = 'users' }) {
  const [tab, setTab] = useState(initialTab)
  const [data, setData] = useState({ users: [], roles: [], permissions: [], tenants: [], logs: [], health: {} })
  const [loading, setLoading] = useState(true)
  const [query, setQuery] = useState('')
  const [filters, setFilters] = useState({ actor: '', from: '', to: '' })
  const [modal, setModal] = useState(null)

  const load = async (logFilters = filters) => {
    setLoading(true)
    try {
      let result = {}
      if (tab === 'users' || tab === 'registration') {
        const [users, roles, tenants] = await Promise.all([api('/users'), api('/roles'), api('/tenants')])
        result = { users, roles, tenants }
      } else if (tab === 'roles') {
        const [roles, permissions] = await Promise.all([api('/roles'), api('/permissions')])
        result = { roles, permissions }
      } else if (tab === 'logs') {
        const params = new URLSearchParams({ limit: '200' })
        if (logFilters.actor) params.set('actor', logFilters.actor)
        if (logFilters.from) params.set('from', `${logFilters.from}T00:00:00`)
        if (logFilters.to) params.set('to', `${logFilters.to}T23:59:59`)
        result = { logs: await api(`/audit-logs?${params}`) }
      } else result = { health: await api('/health') }
      setData(current => ({ ...current, ...result }))
    } catch (error) { notify(error.message) }
    finally { setLoading(false) }
  }
  useEffect(() => { load() }, [tab])

  const run = async (action, message) => {
    try { await action(); setModal(null); notify(message); await load() }
    catch (error) { notify(error.message) }
  }
  const filteredUsers = useMemo(() => data.users.filter(item => `${item.username} ${item.display_name} ${item.email || ''} ${item.roles.map(role => role.name).join(' ')}`.toLowerCase().includes(query.toLowerCase())), [data.users, query])
  const openUser = item => setModal({ type: 'user', item })
  const openRole = item => setModal({ type: 'role', item })

  return <div className="enter-up space-y-5"><section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="flex items-center gap-2 text-[10px] font-medium text-[#41749e]"><ShieldCheck size={13} /> ความปลอดภัยและการตรวจสอบ</div><h2 className="mt-1 text-[25px] font-semibold text-[#152c46]">สิทธิ์ชัดเจน ทุกการเปลี่ยนแปลงมีร่องรอย</h2><p className="mt-1 text-xs text-[#748594]">ผู้ใช้ กลุ่ม สิทธิ์ LDAP/AD และ History Log อย่างน้อย 90 วัน</p></div><div className="flex flex-wrap gap-2">{user?.auth_source === 'local' && <button onClick={() => setModal({ type: 'change-password' })} className="action-secondary"><KeyRound size={15} /> เปลี่ยนรหัสผ่าน</button>}{tab === 'users' && <button onClick={() => openUser(null)} className="action-primary"><Plus size={16} /> เพิ่มผู้ใช้งาน</button>}{tab === 'roles' && <button onClick={() => openRole(null)} className="action-primary"><Plus size={16} /> เพิ่มกลุ่ม</button>}</div></section>
    <section className="overflow-hidden rounded-2xl border border-[#dfe7eb] bg-white"><div className="flex overflow-x-auto border-b border-[#e4eaee] px-5">{tabs.map(([id, label]) => <button key={id} onClick={() => { setTab(id); setQuery('') }} className={`relative min-w-max px-4 py-3 text-xs ${tab === id ? 'font-medium text-[#173653]' : 'text-[#748594]'}`}>{label}{tab === id && <span className="absolute inset-x-3 bottom-0 h-0.5 bg-[#f0b72d]" />}</button>)}</div><div className="p-5">
      {loading ? <Loading /> : <>
        {tab === 'users' && <UsersPanel rows={filteredUsers} query={query} setQuery={setQuery} edit={openUser} reset={item => setModal({ type: 'reset', item })} cancel={item => setModal({ type: 'cancel-user', item })} />}
        {tab === 'roles' && <RolesPanel rows={data.roles} edit={openRole} cancel={item => setModal({ type: 'cancel-role', item })} />}
        {tab === 'registration' && <RegistrationPanel tenants={data.tenants} users={data.users} create={item => setModal({ type: 'portal', item })} reset={(tenant, account) => setModal({ type: 'reset', item: account, tenant })} notify={notify} />}
        {tab === 'ldap' && <DirectoryPanel health={data.health} />}
        {tab === 'logs' && <LogsPanel rows={data.logs} filters={filters} setFilters={setFilters} search={() => load(filters)} />}
      </>}
    </div></section>
    {modal && <AdminDialog modal={modal} roles={data.roles} permissions={data.permissions} close={() => setModal(null)} submit={payload => submitModal(modal, payload, run)} />}
  </div>
}

function UsersPanel({ rows, query, setQuery, edit, reset, cancel }) { return <><Header title="ผู้ใช้งานระบบ" detail="รองรับบัญชี Local และ LDAP โดยไม่จำกัดจำนวน"><label className="search"><Search size={14} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="ค้นหาผู้ใช้งาน" /></label></Header><Table headers={['ผู้ใช้งาน', 'กลุ่ม', 'แหล่งยืนยันตัวตน', 'เข้าใช้ล่าสุด', 'สถานะ', 'ดำเนินการ']}>{rows.map(item => <tr key={item.id}><Cell><b>{item.display_name}</b><small>{item.username} · {item.email || 'ไม่ระบุอีเมล'}</small></Cell><Cell>{item.roles.map(role => role.name).join(', ') || 'ยังไม่กำหนดกลุ่ม'}</Cell><Cell><Badge tone={item.auth_source === 'ldap' ? 'blue' : 'gray'}>{item.auth_source.toUpperCase()}</Badge></Cell><Cell>{dateTime(item.last_login_at)}</Cell><Cell><Badge tone={item.status === 'active' ? 'green' : 'gray'}>{item.status === 'active' ? 'ใช้งาน' : 'ระงับ'}</Badge></Cell><Cell><div className="row-actions"><button title="แก้ไข" onClick={() => edit(item)}><Pencil /></button>{item.auth_source === 'local' && <button title="รีเซ็ตรหัสผ่าน" onClick={() => reset(item)}><KeyRound /></button>}<button title="ยกเลิกผู้ใช้" className="danger" onClick={() => cancel(item)}><Trash2 /></button></div></Cell></tr>)}</Table>{!rows.length && <Empty text="ไม่พบผู้ใช้งาน" />}</> }
function RolesPanel({ rows, edit, cancel }) { return <><Header title="กลุ่มผู้ใช้งานและสิทธิ์" detail="กำหนดสิทธิ์เป็นรายกลุ่มและนำไปใช้กับผู้ใช้งาน"><span className="rounded-full bg-[#edf5fb] px-3 py-1.5 text-[10px] text-[#397caf]">{rows.length} กลุ่ม</span></Header><div className="grid gap-3 lg:grid-cols-3">{rows.map(item => <article key={item.id} className="rounded-2xl border border-[#dce6eb] p-4"><div className="flex items-start justify-between"><span className="grid size-9 place-items-center rounded-xl bg-[#eef4f8] text-[#4f7895]"><Users size={17} /></span><Badge tone="gray">{item.permissions.length} สิทธิ์</Badge></div><h4 className="mt-4 text-sm font-semibold">{item.name}</h4><p className="mt-1 min-h-8 text-[10px] text-[#7b8c99]">{item.description || 'ไม่ระบุรายละเอียด'}</p><div className="mt-3 flex justify-end gap-1 border-t border-[#edf1f3] pt-3"><button onClick={() => edit(item)} className="rounded-lg px-3 py-2 text-[10px] text-[#397caf]">แก้ไขสิทธิ์</button><button onClick={() => cancel(item)} className="rounded-lg px-3 py-2 text-[10px] text-[#b74e44]">ยกเลิก</button></div></article>)}</div></> }
function RegistrationPanel({ tenants, users, create, reset, notify }) { const searchStudent = async event => { event.preventDefault(); const studentId = new FormData(event.currentTarget).get('studentId'); try { const result = await api(`/integrations/students/${encodeURIComponent(studentId)}`); notify(`พบข้อมูล ${result.firstName || result.displayName || studentId}`) } catch (error) { notify(error.message) } }; return <><Header title="การลงทะเบียนเข้าใช้ระบบ" detail="สร้างหรือรีเซ็ตบัญชี Portal สำหรับนักศึกษา บุคลากร และบุคคลภายนอก"><form onSubmit={searchStudent} className="flex gap-2"><input required name="studentId" className={fieldClass} placeholder="รหัสนักศึกษา" /><button className="action-secondary shrink-0"><Search size={14} /> ดึงข้อมูล มสด.</button></form></Header><Table headers={['ผู้เช่า', 'ประเภท', 'บัญชี Portal', 'แหล่งยืนยัน', 'ดำเนินการ']}>{tenants.map(tenant => { const account = users.find(item => item.tenant_id === tenant.id); return <tr key={tenant.id}><Cell><b>{tenant.first_name} {tenant.last_name}</b><small>{tenant.tenant_code}</small></Cell><Cell>{tenantType(tenant.tenant_type)}</Cell><Cell>{account?.username || 'ยังไม่มีบัญชี'}</Cell><Cell>{account?.auth_source?.toUpperCase() || '—'}</Cell><Cell>{account ? <button onClick={() => reset(tenant, account)} className="text-link"><KeyRound size={13} /> รีเซ็ตรหัสผ่าน</button> : <button onClick={() => create(tenant)} className="text-link"><Plus size={13} /> สร้างบัญชี</button>}</Cell></tr> })}</Table>{!tenants.length && <Empty text="ยังไม่มีทะเบียนผู้เช่า" />}</> }
function DirectoryPanel({ health }) { const ready = health.ldapConfigured; return <div className="grid gap-4 lg:grid-cols-[1fr_.8fr]"><section className="rounded-2xl border border-[#dce6eb] p-5"><div className="flex items-center gap-3"><span className={`grid size-11 place-items-center rounded-xl ${ready ? 'bg-[#edf7f4] text-[#2f7d68]' : 'bg-[#fff7e4] text-[#ad7210]'}`}><ServerCog size={21} /></span><div><h3 className="text-sm font-semibold">University LDAP / Active Directory</h3><p className="text-[10px] text-[#81909c]">ยืนยันตัวตนกับฐานข้อมูลผู้ใช้งานกลาง</p></div><Badge tone={ready ? 'green' : 'amber'}>{ready ? 'พร้อมเชื่อมต่อ' : 'ยังไม่กำหนดค่า'}</Badge></div><p className="mt-5 rounded-xl bg-[#f6f9fa] p-4 text-[10px] leading-5 text-[#607687]">กำหนด LDAP_URL, LDAP_BASE_DN และ LDAP_BIND credentials ผ่าน Environment ของ Backend โดยระบบจะไม่จัดเก็บรหัสผ่าน LDAP</p></section><section className="rounded-2xl border border-[#dce6eb] p-5"><h3 className="text-sm font-semibold">นโยบายรหัสผ่าน</h3><div className="mt-4 space-y-3">{[['ความยาวขั้นต่ำ', '8 ตัวอักษร', LockKeyhole], ['รูปแบบ', 'พิมพ์ใหญ่ เล็ก และอักขระพิเศษ', KeyRound], ['Local password', 'bcrypt cost 12', ShieldCheck], ['Session', 'JWT อายุ 8 ชั่วโมง', Clock3]].map(([label, value, Icon]) => <div key={label} className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-[#eef4f7] text-[#527994]"><Icon size={14} /></span><div><p className="text-[9px] text-[#738594]">{label}</p><p className="text-[11px] font-medium">{value}</p></div><CheckCircle2 size={15} className="ml-auto text-[#2f7d68]" /></div>)}</div></section></div> }
function LogsPanel({ rows, filters, setFilters, search }) { return <><Header title="ประวัติการใช้งาน" detail="ค้นหาตามชื่อผู้ใช้และช่วงวันที่ · เก็บย้อนหลังอย่างน้อย 90 วัน"><div className="flex flex-wrap gap-2"><input value={filters.actor} onChange={event => setFilters(current => ({ ...current, actor: event.target.value }))} className={fieldClass} placeholder="ชื่อผู้ใช้งาน" /><input type="date" value={filters.from} onChange={event => setFilters(current => ({ ...current, from: event.target.value }))} className={fieldClass} /><input type="date" value={filters.to} onChange={event => setFilters(current => ({ ...current, to: event.target.value }))} className={fieldClass} /><button onClick={search} className="action-secondary"><Search size={14} /> ค้นหา</button></div></Header><Table headers={['เวลา', 'ผู้ใช้งาน', 'เหตุการณ์', 'ข้อมูล', 'IP Address']}>{rows.map(item => <tr key={item.id}><Cell>{dateTime(item.created_at)}</Cell><Cell><b>{item.actor_username}</b></Cell><Cell><Badge tone="blue">{item.action}</Badge></Cell><Cell>{item.entity_type} · {item.entity_id || '—'}</Cell><Cell>{item.ip_address || '—'}</Cell></tr>)}</Table>{!rows.length && <Empty text="ไม่พบประวัติการใช้งานตามเงื่อนไข" />}</> }

function AdminDialog({ modal, roles, permissions, close, submit }) { const [saving, setSaving] = useState(false); const selectedRoles = new Set(modal.item?.roles?.map(role => role.id) || []), selectedPermissions = new Set(modal.item?.permissions?.map(permission => permission.id) || []); const handle = async event => { event.preventDefault(); setSaving(true); try { const form = new FormData(event.currentTarget); const payload = Object.fromEntries(form); payload.roleIds = form.getAll('roleIds').map(Number); payload.permissionIds = form.getAll('permissionIds').map(Number); await submit(payload) } finally { setSaving(false) } }; const title = { user: modal.item ? 'แก้ไขผู้ใช้งาน' : 'เพิ่มผู้ใช้งาน', role: modal.item ? 'แก้ไขกลุ่มและสิทธิ์' : 'เพิ่มกลุ่มผู้ใช้งาน', reset: 'รีเซ็ตรหัสผ่าน', portal: 'สร้างบัญชี Portal', 'change-password': 'เปลี่ยนรหัสผ่านของฉัน', 'cancel-user': 'ยกเลิกผู้ใช้งาน', 'cancel-role': 'ยกเลิกกลุ่มผู้ใช้งาน' }[modal.type]; return <div className="fixed inset-0 z-50 grid place-items-end bg-[#142a46]/45 sm:place-items-center sm:p-4" onMouseDown={event => event.target === event.currentTarget && close()}><form onSubmit={handle} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-white shadow-2xl sm:rounded-3xl"><div className="flex items-center border-b border-[#e5ebef] p-5"><div><p className="text-[10px] font-semibold text-[#397caf]">ผู้ใช้และสิทธิ์ 4.3</p><h3 className="mt-1 text-base font-semibold">{title}</h3></div><button type="button" onClick={close} className="ml-auto grid size-9 place-items-center rounded-full bg-[#f2f5f7]"><X size={17} /></button></div><div className="grid gap-4 p-5">
      {modal.type === 'user' && <><div className="grid grid-cols-2 gap-3"><Field label="Username"><input required disabled={Boolean(modal.item)} name="username" defaultValue={modal.item?.username} className={fieldClass} /></Field><Field label="ชื่อที่แสดง"><input required name="displayName" defaultValue={modal.item?.display_name} className={fieldClass} /></Field></div><Field label="E-mail"><input type="email" name="email" defaultValue={modal.item?.email} className={fieldClass} /></Field>{!modal.item && <div className="grid grid-cols-2 gap-3"><Field label="แหล่งยืนยันตัวตน"><select name="authSource" className={fieldClass}><option value="local">Local</option><option value="ldap">LDAP</option></select></Field><Field label="รหัสผ่าน Local"><input type="password" name="password" className={fieldClass} placeholder="อย่างน้อย 8 ตัวอักษร" /></Field></div>}<CheckGrid title="กลุ่มผู้ใช้งาน" name="roleIds" rows={roles} selected={selectedRoles} /></>}
      {modal.type === 'role' && <><Field label="ชื่อกลุ่ม"><input required name="name" defaultValue={modal.item?.name} className={fieldClass} /></Field><Field label="รายละเอียด"><textarea name="description" defaultValue={modal.item?.description} rows="3" className={`${fieldClass} h-auto py-3`} /></Field><CheckGrid title="สิทธิ์การใช้งานของกลุ่ม" name="permissionIds" rows={permissions} selected={selectedPermissions} showCode /></>}
      {modal.type === 'portal' && <><p className="rounded-xl bg-[#f5f8fa] p-3 text-xs">{modal.item.tenant_code} · {modal.item.first_name} {modal.item.last_name}</p><Field label="Username"><input required minLength="3" name="username" defaultValue={modal.item.tenant_code.toLowerCase()} className={fieldClass} /></Field><Field label="รหัสผ่านเริ่มต้น"><input required type="password" name="newPassword" className={fieldClass} /></Field></>}
      {modal.type === 'reset' && <><p className="rounded-xl bg-[#f5f8fa] p-3 text-xs">{modal.item.username} · {modal.item.display_name}</p><Field label="รหัสผ่านใหม่"><input required type="password" name="newPassword" className={fieldClass} /></Field></>}
      {modal.type === 'change-password' && <><Field label="รหัสผ่านปัจจุบัน"><input required type="password" name="currentPassword" className={fieldClass} /></Field><Field label="รหัสผ่านใหม่"><input required type="password" name="newPassword" className={fieldClass} /></Field></>}
      {modal.type.startsWith('cancel-') && <Field label="เหตุผลการยกเลิก (บังคับ)"><textarea required minLength="5" name="reason" rows="4" className={`${fieldClass} h-auto py-3`} /></Field>}
    </div><div className="flex gap-2 border-t border-[#e5ebef] p-4"><button type="button" onClick={close} className="flex-1 rounded-xl border border-[#d8e2e7] py-2.5 text-xs">ปิด</button><button disabled={saving} className={`flex flex-1 items-center justify-center gap-2 rounded-xl py-2.5 text-xs font-semibold ${modal.type.startsWith('cancel-') ? 'bg-[#b74e44] text-white' : 'bg-[#f5bf3c] text-[#173653]'}`}>{saving && <LoaderCircle size={14} className="animate-spin" />} ยืนยันรายการ</button></div></form></div> }

async function submitModal(modal, payload, run) { if (modal.type === 'user') return run(() => api(modal.item ? `/users/${modal.item.id}` : '/users', { method: modal.item ? 'PATCH' : 'POST', body: modal.item ? { displayName: payload.displayName, email: payload.email || null, roleIds: payload.roleIds } : { username: payload.username, displayName: payload.displayName, email: payload.email || null, authSource: payload.authSource, password: payload.password || undefined, roleIds: payload.roleIds } }), modal.item ? 'แก้ไขผู้ใช้งานแล้ว' : 'เพิ่มผู้ใช้งานแล้ว'); if (modal.type === 'role') return run(() => api(modal.item ? `/roles/${modal.item.id}` : '/roles', { method: modal.item ? 'PATCH' : 'POST', body: { name: payload.name, description: payload.description || null, permissionIds: payload.permissionIds } }), modal.item ? 'แก้ไขกลุ่มและสิทธิ์แล้ว' : 'เพิ่มกลุ่มผู้ใช้งานแล้ว'); if (modal.type === 'portal') return run(() => api(`/tenants/${modal.item.id}/portal-account`, { method: 'POST', body: { username: payload.username, password: payload.newPassword } }), 'สร้างบัญชี Portal แล้ว'); if (modal.type === 'reset') return run(() => api(`/users/${modal.item.id}/reset-password`, { method: 'POST', body: { newPassword: payload.newPassword } }), 'รีเซ็ตรหัสผ่านแล้ว'); if (modal.type === 'change-password') return run(() => api('/auth/change-password', { method: 'POST', body: { currentPassword: payload.currentPassword, newPassword: payload.newPassword } }), 'เปลี่ยนรหัสผ่านแล้ว'); const entity = modal.type === 'cancel-user' ? 'users' : 'roles'; return run(() => api(`/${entity}/${modal.item.id}`, { method: 'DELETE', body: { reason: payload.reason } }), 'ยกเลิกรายการพร้อมบันทึกเหตุผลแล้ว') }

function CheckGrid({ title, name, rows, selected, showCode }) { return <fieldset><legend className="mb-2 text-[10px] font-medium text-[#617688]">{title}</legend><div className="grid max-h-64 gap-2 overflow-y-auto rounded-xl border border-[#dce5ea] p-3 sm:grid-cols-2">{rows.map(item => <label key={item.id} className="flex items-start gap-2 rounded-lg bg-[#f7f9fa] p-2 text-[10px]"><input type="checkbox" name={name} value={item.id} defaultChecked={selected.has(item.id)} className="mt-0.5" /><span><b>{item.name}</b>{showCode && <small className="block font-['IBM_Plex_Sans'] text-[8px] text-[#82919c]">{item.code}</small>}</span></label>)}</div></fieldset> }
function Header({ title, detail, children }) { return <div className="mb-4 flex flex-col justify-between gap-3 xl:flex-row xl:items-end"><div><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 text-[10px] text-[#81909c]">{detail}</p></div>{children}</div> }
function Table({ headers, children }) { return <div className="overflow-x-auto rounded-xl border border-[#e0e8ec]"><table className="w-full min-w-[820px] text-left text-[11px]"><thead className="bg-[#f8fafb] text-[#718392]"><tr>{headers.map(item => <th key={item} className="px-4 py-3 font-medium">{item}</th>)}</tr></thead><tbody className="divide-y divide-[#edf1f3]">{children}</tbody></table></div> }
function Cell({ children }) { return <td className="px-4 py-3 align-top text-[#5f7485]">{children}</td> }
function Field({ label, children }) { return <label><span className="mb-1.5 block text-[10px] font-medium text-[#617688]">{label}</span>{children}</label> }
function Badge({ children, tone }) { const tones = { green: 'bg-[#edf7f4] text-[#2f7d68]', blue: 'bg-[#edf5fb] text-[#397caf]', amber: 'bg-[#fff7e4] text-[#ad7210]', gray: 'bg-[#f1f3f5] text-[#6e7d89]' }; return <span className={`ml-auto inline-block rounded-full px-2.5 py-1 text-[9px] ${tones[tone]}`}>{children}</span> }
function Loading() { return <div className="grid min-h-64 place-items-center"><LoaderCircle className="animate-spin text-[#397caf]" /></div> }
function Empty({ text }) { return <p className="py-12 text-center text-xs text-[#82919c]">{text}</p> }
function dateTime(value) { return value ? new Date(value).toLocaleString('th-TH', { dateStyle: 'medium', timeStyle: 'short' }) : 'ยังไม่เคยเข้าใช้' }
function tenantType(value) { return ({ student: 'นักศึกษา', staff: 'บุคลากร', external: 'บุคคลภายนอก' })[value] || value }

export default Administration
