import { useState } from 'react'
import { CheckCircle2, Clock3, KeyRound, LockKeyhole, Plus, Search, ServerCog, ShieldCheck, UserCog, Users } from 'lucide-react'

const users=[
 {user:'supawadee.p',name:'สุภาวดี พรหมมา',group:'เจ้าหน้าที่หอพัก',source:'LDAP',status:'ใช้งาน',login:'27 ก.ค. 15:38'},
 {user:'finance01',name:'กนกวรรณ ใจดี',group:'เจ้าหน้าที่การเงิน',source:'LDAP',status:'ใช้งาน',login:'27 ก.ค. 14:12'},
 {user:'admin',name:'ผู้ดูแลระบบ',group:'ผู้ดูแลระบบ',source:'Local',status:'ใช้งาน',login:'27 ก.ค. 09:05'},
 {user:'65010234',name:'ณัฐชา แสงทอง',group:'ผู้เช่า',source:'LDAP',status:'ใช้งาน',login:'26 ก.ค. 20:41'},
]
const logs=[
 ['15:38:22','supawadee.p','LOGIN_SUCCESS','เข้าสู่ระบบผ่าน LDAP','172.16.4.21'],
 ['15:32:08','supawadee.p','PAYMENT_RECEIVED','รับชำระ INV-6907-0842','172.16.4.21'],
 ['15:32:09','supawadee.p','CREATE','ออกใบเสร็จ RC-690727-0142','172.16.4.21'],
 ['14:56:42','finance01','UPDATE','แก้ไขอัตราค่าไฟฟ้า','172.16.4.18'],
 ['13:21:06','admin','PASSWORD_RESET','รีเซ็ตรหัสผ่าน EXT0098','172.16.1.10'],
]
function Administration({notify,initialTab='users'}){const[tab,setTab]=useState(initialTab);return <div className="enter-up space-y-5"><section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="flex items-center gap-2 text-[10px] font-medium text-[#41749e]"><ShieldCheck size={13}/> ความปลอดภัยและการตรวจสอบ</div><h2 className="mt-1 text-[25px] font-semibold text-[#152c46]">สิทธิ์ชัดเจน ทุกการเปลี่ยนแปลงมีร่องรอย</h2><p className="mt-1 text-xs text-[#748594]">ผู้ใช้ กลุ่ม สิทธิ์ LDAP/AD และ History Log อย่างน้อย 90 วัน</p></div>{tab==='users'&&<button onClick={()=>notify('เปิดแบบฟอร์มเพิ่มผู้ใช้งาน')} className="flex items-center gap-2 rounded-xl bg-[#f5bf3c] px-4 py-2.5 text-xs font-semibold text-[#173653]"><Plus size={16}/> เพิ่มผู้ใช้งาน</button>}</section>
 <section className="overflow-hidden rounded-2xl border border-[#dfe7eb] bg-white"><div className="flex overflow-x-auto border-b border-[#e4eaee] px-5">{[['users','ผู้ใช้งาน'],['roles','กลุ่มและสิทธิ์'],['ldap','LDAP / AD'],['logs','History Log']].map(x=><button key={x[0]} onClick={()=>setTab(x[0])} className={`relative min-w-max px-4 py-3 text-xs ${tab===x[0]?'font-medium text-[#173653]':'text-[#748594]'}`}>{x[1]}{tab===x[0]&&<span className="absolute inset-x-3 bottom-0 h-0.5 bg-[#f0b72d]"/>}</button>)}</div><div className="p-5">
 {tab==='users'&&<><div className="mb-4 flex items-center"><div><h3 className="text-sm font-semibold">ผู้ใช้งานระบบ</h3><p className="text-[10px] text-[#81909c]">รองรับจำนวนผู้ใช้ไม่จำกัด</p></div><label className="ml-auto flex h-9 items-center gap-2 rounded-xl border border-[#d8e2e7] px-3"><Search size={14}/><input className="w-44 text-[11px] outline-none" placeholder="ค้นหาผู้ใช้งาน"/></label></div><div className="overflow-x-auto rounded-xl border border-[#e0e8ec]"><table className="w-full min-w-[760px] text-left"><thead className="bg-[#f8fafb] text-[10px] text-[#718392]"><tr><th className="px-4 py-3">ผู้ใช้งาน</th><th className="px-4 py-3">กลุ่ม</th><th className="px-4 py-3">แหล่งยืนยันตัวตน</th><th className="px-4 py-3">เข้าใช้ล่าสุด</th><th className="px-4 py-3">สถานะ</th><th></th></tr></thead><tbody className="divide-y divide-[#edf1f3]">{users.map(x=><tr key={x.user} className="text-xs"><td className="px-4 py-3"><p className="font-medium">{x.name}</p><p className="font-['IBM_Plex_Sans'] text-[10px] text-[#82919d]">{x.user}</p></td><td className="px-4 py-3 text-[#5f7485]">{x.group}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-[10px] ${x.source==='LDAP'?'bg-[#edf5fb] text-[#397caf]':'bg-[#f1f3f5] text-[#6e7d89]'}`}>{x.source}</span></td><td className="px-4 py-3 font-['IBM_Plex_Sans'] text-[11px] text-[#607687]">{x.login}</td><td className="px-4 py-3"><span className="text-[10px] text-[#2f7d68]">● {x.status}</span></td><td className="px-4 py-3"><button onClick={()=>notify(`เปิดข้อมูล ${x.name}`)} className="text-[10px] text-[#397caf]">จัดการ</button></td></tr>)}</tbody></table></div></>}
 {tab==='roles'&&<div><div className="mb-4 flex items-center justify-between"><div><h3 className="text-sm font-semibold">กลุ่มผู้ใช้งานและสิทธิ์</h3><p className="text-[10px] text-[#81909c]">กำหนดสิทธิ์ตามหน้าที่ โดยไม่ผูกกับรายบุคคล</p></div><button onClick={()=>notify('เปิดแบบฟอร์มเพิ่มกลุ่ม')} className="flex items-center gap-1 text-[10px] text-[#397caf]"><Plus size={13}/> เพิ่มกลุ่ม</button></div><div className="grid gap-3 lg:grid-cols-3">{[['ผู้ดูแลระบบ','18 สิทธิ์','เข้าถึงทุกโมดูล'],['เจ้าหน้าที่การเงิน','7 สิทธิ์','การเงิน รับชำระ รายงาน'],['เจ้าหน้าที่หอพัก','11 สิทธิ์','ผู้เช่า ห้อง สัญญา ซ่อม'],['ช่างซ่อมบำรุง','3 สิทธิ์','งานซ่อมและสต็อกช่าง'],['ผู้เช่า','2 สิทธิ์','ดูรายการและเอกสารของตนเอง']].map(x=><button key={x[0]} onClick={()=>notify(`แก้ไขสิทธิ์กลุ่ม ${x[0]}`)} className="rounded-2xl border border-[#dce6eb] p-4 text-left hover:border-[#aac3d2]"><div className="flex items-start justify-between"><div className="grid size-9 place-items-center rounded-xl bg-[#eef4f8] text-[#4f7895]"><Users size={17}/></div><span className="rounded-full bg-[#f2f5f7] px-2 py-1 text-[9px] text-[#6c7e8b]">{x[1]}</span></div><h4 className="mt-4 text-sm font-semibold">{x[0]}</h4><p className="mt-1 text-[10px] text-[#7b8c99]">{x[2]}</p></button>)}</div></div>}
 {tab==='ldap'&&<div className="grid gap-4 lg:grid-cols-[1fr_.8fr]"><section className="rounded-2xl border border-[#dce6eb] p-5"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-[#edf7f4] text-[#2f7d68]"><ServerCog size={21}/></div><div><h3 className="text-sm font-semibold">University Active Directory</h3><p className="text-[10px] text-[#81909c]">ldaps://ad.university.ac.th:636</p></div><span className="ml-auto rounded-full bg-[#edf7f4] px-2.5 py-1 text-[10px] text-[#2f7d68]">พร้อมเชื่อมต่อ</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[['Base DN','DC=university,DC=ac,DC=th'],['User attribute','sAMAccountName'],['Email attribute','mail'],['Encryption','LDAPS / TLS 1.3']].map(x=><div key={x[0]} className="rounded-xl bg-[#f6f9fa] p-3"><p className="text-[9px] text-[#7b8c99]">{x[0]}</p><p className="mt-1 break-all font-['IBM_Plex_Sans'] text-[10px] font-medium">{x[1]}</p></div>)}</div></section><section className="rounded-2xl border border-[#dce6eb] p-5"><h3 className="text-sm font-semibold">นโยบายรหัสผ่าน</h3><div className="mt-4 space-y-3">{[['ความยาวขั้นต่ำ','8 ตัวอักษร',LockKeyhole],['จัดเก็บ Local password','bcrypt cost 12',KeyRound],['LDAP password','ไม่จัดเก็บในระบบ',ShieldCheck],['Session','JWT อายุ 8 ชั่วโมง',Clock3]].map(([a,b,I])=><div key={a} className="flex items-center gap-3"><div className="grid size-8 place-items-center rounded-lg bg-[#eef4f7] text-[#527994]"><I size={14}/></div><div><p className="text-[10px] text-[#738594]">{a}</p><p className="text-xs font-medium">{b}</p></div><CheckCircle2 size={15} className="ml-auto text-[#2f7d68]"/></div>)}</div></section></div>}
 {tab==='logs'&&<div><div className="mb-4 flex items-center"><div><h3 className="text-sm font-semibold">ประวัติการใช้งาน</h3><p className="text-[10px] text-[#81909c]">เก็บออนไลน์อย่างน้อย 90 วัน · Login, Configuration, เพิ่ม, แก้ไข, ลบ, ยกเลิก</p></div><span className="ml-auto rounded-full bg-[#edf7f4] px-3 py-1.5 text-[10px] text-[#2f7d68]">Retention 90 วัน</span></div><div className="overflow-x-auto rounded-xl border border-[#e0e8ec]"><table className="w-full min-w-[820px] text-left"><thead className="bg-[#f8fafb] text-[10px] text-[#718392]"><tr><th className="px-4 py-3">เวลา</th><th className="px-4 py-3">ผู้ใช้งาน</th><th className="px-4 py-3">เหตุการณ์</th><th className="px-4 py-3">รายละเอียด</th><th className="px-4 py-3">IP Address</th></tr></thead><tbody className="divide-y divide-[#edf1f3]">{logs.map(x=><tr key={`${x[0]}${x[1]}`} className="text-[11px]"><td className="px-4 py-3 font-['IBM_Plex_Sans']">{x[0]}</td><td className="px-4 py-3 font-medium">{x[1]}</td><td className="px-4 py-3"><span className="rounded bg-[#eef4f7] px-2 py-1 font-['IBM_Plex_Sans'] text-[9px] text-[#4d7089]">{x[2]}</span></td><td className="px-4 py-3 text-[#5f7485]">{x[3]}</td><td className="px-4 py-3 font-['IBM_Plex_Sans'] text-[#718493]">{x[4]}</td></tr>)}</tbody></table></div></div>}
 </div></section></div>}
export default Administration
